// ============================================================
// HireFlow — Demo Seed Data Generator
// ============================================================
import type {
  User, Company, CompanyMember, Job, Application,
  CandidateProfile, CandidateMatch, Interview, Notification,
  JobRequirement, ScreeningConfig
} from '../types';

function genId(): string {
  return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
}

const DEMO_IDS = {
  // Companies
  companyA: 'comp-alpha-tech',
  companyB: 'comp-beta-solutions',
  // Users
  bhrA: 'user-bhr-alpha',
  hrA: 'user-hr-alpha',
  interviewerA1: 'user-int-alpha1',
  interviewerA2: 'user-int-alpha2',
  bhrB: 'user-bhr-beta',
  candidate1: 'user-cand-1',
  candidate2: 'user-cand-2',
  candidate3: 'user-cand-3',
  admin: 'user-admin',
  // Jobs
  jobA1: 'job-backend-dev',
  jobA2: 'job-frontend-dev',
  jobB1: 'job-data-eng',
};

export function generateDemoData() {
  const users: User[] = [
    {
      id: DEMO_IDS.admin,
      email: 'demo-admin@hireflow.com',
      displayName: 'Admin User',
      role: 'PLATFORM_ADMIN',
      status: 'active',
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    {
      id: DEMO_IDS.bhrA,
      email: 'demo-bhr@example.com',
      displayName: 'Rajesh Kumar',
      role: 'BHR_MANAGER',
      companyId: DEMO_IDS.companyA,
      status: 'active',
      createdAt: '2026-01-15T00:00:00Z',
      updatedAt: '2026-01-15T00:00:00Z',
    },
    {
      id: DEMO_IDS.hrA,
      email: 'demo-hr@example.com',
      displayName: 'Anita Desai',
      role: 'HR_RECRUITER',
      companyId: DEMO_IDS.companyA,
      status: 'active',
      createdAt: '2026-02-01T00:00:00Z',
      updatedAt: '2026-02-01T00:00:00Z',
    },
    {
      id: DEMO_IDS.interviewerA1,
      email: 'demo-interviewer@example.com',
      displayName: 'Vikram Singh',
      role: 'INTERVIEWER',
      companyId: DEMO_IDS.companyA,
      status: 'active',
      createdAt: '2026-02-10T00:00:00Z',
      updatedAt: '2026-02-10T00:00:00Z',
    },
    {
      id: DEMO_IDS.interviewerA2,
      email: 'interviewer2@example.com',
      displayName: 'Sneha Patel',
      role: 'INTERVIEWER',
      companyId: DEMO_IDS.companyA,
      status: 'active',
      createdAt: '2026-02-10T00:00:00Z',
      updatedAt: '2026-02-10T00:00:00Z',
    },
    {
      id: DEMO_IDS.bhrB,
      email: 'bhr-beta@example.com',
      displayName: 'Meera Nair',
      role: 'BHR_MANAGER',
      companyId: DEMO_IDS.companyB,
      status: 'active',
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    {
      id: DEMO_IDS.candidate1,
      email: 'demo-candidate@example.com',
      displayName: 'Arjun Mehta',
      role: 'CANDIDATE',
      status: 'active',
      createdAt: '2026-03-10T00:00:00Z',
      updatedAt: '2026-03-10T00:00:00Z',
    },
    {
      id: DEMO_IDS.candidate2,
      email: 'candidate2@example.com',
      displayName: 'Priya Sharma',
      role: 'CANDIDATE',
      status: 'active',
      createdAt: '2026-03-12T00:00:00Z',
      updatedAt: '2026-03-12T00:00:00Z',
    },
    {
      id: DEMO_IDS.candidate3,
      email: 'candidate3@example.com',
      displayName: 'Rohit Verma',
      role: 'CANDIDATE',
      status: 'active',
      createdAt: '2026-03-15T00:00:00Z',
      updatedAt: '2026-03-15T00:00:00Z',
    },
  ];

  const companies: Company[] = [
    {
      id: DEMO_IDS.companyA,
      name: 'Alpha Technologies',
      description: 'A leading software development company specializing in cloud-native enterprise solutions, microservices architecture, and AI-powered applications.',
      industry: 'Information Technology',
      website: 'https://alphatech.example.com',
      location: 'Bangalore, India',
      size: '200-500',
      foundedYear: 2018,
      createdAt: '2026-01-15T00:00:00Z',
      updatedAt: '2026-01-15T00:00:00Z',
    },
    {
      id: DEMO_IDS.companyB,
      name: 'Beta Solutions',
      description: 'Data analytics and business intelligence company providing end-to-end data solutions for enterprises across fintech and healthcare.',
      industry: 'Data Analytics',
      website: 'https://betasolutions.example.com',
      location: 'Hyderabad, India',
      size: '50-200',
      foundedYear: 2020,
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
  ];

  const companyMembers: CompanyMember[] = [
    { id: 'mem-1', userId: DEMO_IDS.bhrA, companyId: DEMO_IDS.companyA, role: 'BHR_MANAGER', permissions: ['all'], joinedAt: '2026-01-15T00:00:00Z' },
    { id: 'mem-2', userId: DEMO_IDS.hrA, companyId: DEMO_IDS.companyA, role: 'HR_RECRUITER', permissions: ['view_jobs', 'view_applications', 'manage_candidates', 'schedule_interviews'], joinedAt: '2026-02-01T00:00:00Z' },
    { id: 'mem-3', userId: DEMO_IDS.interviewerA1, companyId: DEMO_IDS.companyA, role: 'INTERVIEWER', permissions: ['view_assigned_interviews'], joinedAt: '2026-02-10T00:00:00Z' },
    { id: 'mem-4', userId: DEMO_IDS.interviewerA2, companyId: DEMO_IDS.companyA, role: 'INTERVIEWER', permissions: ['view_assigned_interviews'], joinedAt: '2026-02-10T00:00:00Z' },
    { id: 'mem-5', userId: DEMO_IDS.bhrB, companyId: DEMO_IDS.companyB, role: 'BHR_MANAGER', permissions: ['all'], joinedAt: '2026-03-01T00:00:00Z' },
  ];

  const backendRequirements: JobRequirement[] = [
    { id: 'req-1', jobId: DEMO_IDS.jobA1, name: 'Java', category: 'skill', priority: 'MANDATORY', weight: 25, description: 'Strong Java programming skills' },
    { id: 'req-2', jobId: DEMO_IDS.jobA1, name: 'Spring Boot', category: 'technology', priority: 'MANDATORY', weight: 20, description: 'Experience with Spring Boot framework' },
    { id: 'req-3', jobId: DEMO_IDS.jobA1, name: 'SQL / PostgreSQL', category: 'skill', priority: 'MANDATORY', weight: 15 },
    { id: 'req-4', jobId: DEMO_IDS.jobA1, name: 'REST API Development', category: 'skill', priority: 'MANDATORY', weight: 10 },
    { id: 'req-5', jobId: DEMO_IDS.jobA1, name: '2+ years experience', category: 'experience', priority: 'MANDATORY', weight: 15 },
    { id: 'req-6', jobId: DEMO_IDS.jobA1, name: 'Docker / Kubernetes', category: 'technology', priority: 'PREFERRED', weight: 8 },
    { id: 'req-7', jobId: DEMO_IDS.jobA1, name: 'AWS / Cloud', category: 'technology', priority: 'PREFERRED', weight: 5 },
    { id: 'req-8', jobId: DEMO_IDS.jobA1, name: 'Microservices Architecture', category: 'domain', priority: 'OPTIONAL', weight: 2 },
  ];

  const frontendRequirements: JobRequirement[] = [
    { id: 'req-f1', jobId: DEMO_IDS.jobA2, name: 'React', category: 'skill', priority: 'MANDATORY', weight: 30 },
    { id: 'req-f2', jobId: DEMO_IDS.jobA2, name: 'TypeScript', category: 'skill', priority: 'MANDATORY', weight: 20 },
    { id: 'req-f3', jobId: DEMO_IDS.jobA2, name: 'CSS / Tailwind', category: 'skill', priority: 'MANDATORY', weight: 15 },
    { id: 'req-f4', jobId: DEMO_IDS.jobA2, name: 'State Management', category: 'skill', priority: 'PREFERRED', weight: 10 },
    { id: 'req-f5', jobId: DEMO_IDS.jobA2, name: '1+ year experience', category: 'experience', priority: 'MANDATORY', weight: 15 },
    { id: 'req-f6', jobId: DEMO_IDS.jobA2, name: 'Testing (Jest/RTL)', category: 'skill', priority: 'PREFERRED', weight: 10 },
  ];

  const defaultScreening: ScreeningConfig = {
    autoResumeExtraction: true,
    skillMatching: true,
    experienceMatching: true,
    educationMatching: true,
    projectRelevance: true,
    certificationMatching: true,
    aiExplanation: true,
    minimumThreshold: 70,
    autoShortlist: false,
  };

  const jobs: Job[] = [
    {
      id: DEMO_IDS.jobA1,
      companyId: DEMO_IDS.companyA,
      title: 'Backend Developer',
      department: 'Engineering',
      employmentType: 'full-time',
      workMode: 'hybrid',
      location: 'Bangalore, India',
      salaryMin: 800000,
      salaryMax: 1500000,
      salaryCurrency: 'INR',
      openings: 3,
      deadline: '2026-10-30T00:00:00Z',
      summary: 'We are looking for a skilled Backend Developer to join our platform engineering team. You will design and build high-performance microservices using Java and Spring Boot, work with PostgreSQL databases, and deploy to cloud infrastructure.',
      responsibilities: [
        'Design and develop RESTful APIs using Spring Boot',
        'Write efficient SQL queries and manage database schemas',
        'Implement microservices architecture patterns',
        'Participate in code reviews and technical design discussions',
        'Deploy and monitor services on cloud infrastructure',
        'Collaborate with frontend and DevOps teams',
      ],
      dayToDay: [
        'Morning standup with the platform team',
        'Implement and test backend features',
        'Review pull requests from team members',
        'Work with product team on requirements',
      ],
      teamDescription: 'You will join a team of 8 engineers building our core platform services.',
      requirements: backendRequirements,
      screeningConfig: defaultScreening,
      status: 'published',
      createdAt: '2026-08-01T00:00:00Z',
      updatedAt: '2026-08-15T00:00:00Z',
      publishedAt: '2026-08-15T00:00:00Z',
    },
    {
      id: DEMO_IDS.jobA2,
      companyId: DEMO_IDS.companyA,
      title: 'Frontend Developer',
      department: 'Engineering',
      employmentType: 'full-time',
      workMode: 'remote',
      location: 'Remote (India)',
      salaryMin: 700000,
      salaryMax: 1200000,
      salaryCurrency: 'INR',
      openings: 2,
      deadline: '2026-11-15T00:00:00Z',
      summary: 'Join our frontend team to build modern, responsive user interfaces using React and TypeScript. You will work on customer-facing applications with a focus on performance and user experience.',
      responsibilities: [
        'Build responsive UI components using React and TypeScript',
        'Implement state management solutions',
        'Write unit and integration tests',
        'Optimize frontend performance',
        'Collaborate with designers on UI/UX implementation',
      ],
      requirements: frontendRequirements,
      screeningConfig: defaultScreening,
      status: 'published',
      createdAt: '2026-08-20T00:00:00Z',
      updatedAt: '2026-09-01T00:00:00Z',
      publishedAt: '2026-09-01T00:00:00Z',
    },
    {
      id: DEMO_IDS.jobB1,
      companyId: DEMO_IDS.companyB,
      title: 'Data Engineer',
      department: 'Data Platform',
      employmentType: 'full-time',
      workMode: 'onsite',
      location: 'Hyderabad, India',
      salaryMin: 1000000,
      salaryMax: 1800000,
      salaryCurrency: 'INR',
      openings: 1,
      summary: 'We need a Data Engineer to design and maintain our data pipelines. You will work with Apache Spark, Airflow, and cloud data warehouses to process millions of records daily.',
      responsibilities: [
        'Build and optimize ETL/ELT data pipelines',
        'Work with Apache Spark and Airflow',
        'Manage cloud data warehouses (BigQuery/Redshift)',
        'Ensure data quality and reliability',
        'Create data models and documentation',
      ],
      requirements: [
        { id: 'req-d1', jobId: DEMO_IDS.jobB1, name: 'Python', category: 'skill', priority: 'MANDATORY', weight: 25 },
        { id: 'req-d2', jobId: DEMO_IDS.jobB1, name: 'Apache Spark', category: 'technology', priority: 'MANDATORY', weight: 20 },
        { id: 'req-d3', jobId: DEMO_IDS.jobB1, name: 'SQL', category: 'skill', priority: 'MANDATORY', weight: 20 },
        { id: 'req-d4', jobId: DEMO_IDS.jobB1, name: 'Airflow', category: 'technology', priority: 'PREFERRED', weight: 15 },
        { id: 'req-d5', jobId: DEMO_IDS.jobB1, name: '3+ years experience', category: 'experience', priority: 'MANDATORY', weight: 20 },
      ],
      screeningConfig: defaultScreening,
      status: 'published',
      createdAt: '2026-09-01T00:00:00Z',
      updatedAt: '2026-09-05T00:00:00Z',
      publishedAt: '2026-09-05T00:00:00Z',
    },
  ];

  const candidateProfiles: CandidateProfile[] = [
    {
      id: 'prof-1',
      userId: DEMO_IDS.candidate1,
      headline: 'Full Stack Developer | Java & React',
      summary: 'Passionate software developer with 3 years of experience building scalable web applications. Proficient in Java, Spring Boot, React, and cloud technologies.',
      phone: '+91-9876543210',
      location: 'Bangalore, India',
      linkedIn: 'https://linkedin.com/in/arjunmehta',
      skills: ['Java', 'Spring Boot', 'React', 'TypeScript', 'PostgreSQL', 'REST APIs', 'Docker', 'Git', 'Agile'],
      experience: [
        {
          id: 'exp-1',
          title: 'Software Developer',
          company: 'TechCorp India',
          location: 'Bangalore',
          startDate: '2024-01-01',
          endDate: '',
          current: true,
          description: 'Developed RESTful APIs using Spring Boot and managed PostgreSQL databases. Built microservices serving 10K+ requests/minute. Implemented CI/CD pipelines with Docker and Jenkins.',
        },
        {
          id: 'exp-2',
          title: 'Junior Developer',
          company: 'StartupXYZ',
          location: 'Pune',
          startDate: '2023-01-01',
          endDate: '2023-12-31',
          current: false,
          description: 'Built full-stack features using Java backend and React frontend. Wrote unit tests achieving 85% code coverage.',
        },
      ],
      education: [
        {
          id: 'edu-1',
          degree: 'B.Tech',
          field: 'Computer Science',
          institution: 'VIT University',
          startDate: '2019-07-01',
          endDate: '2023-06-30',
          grade: '8.5 CGPA',
        },
      ],
      projects: [
        {
          id: 'proj-1',
          name: 'E-Commerce Platform',
          description: 'Built a full-stack e-commerce platform with Spring Boot backend, React frontend, and PostgreSQL database. Implemented payment integration and order management.',
          technologies: ['Java', 'Spring Boot', 'React', 'PostgreSQL', 'Docker'],
          url: 'https://github.com/arjun/ecommerce',
        },
      ],
      certifications: ['AWS Cloud Practitioner'],
      technologies: ['Java', 'Spring Boot', 'React', 'TypeScript', 'PostgreSQL', 'Docker', 'AWS', 'Jenkins'],
      resumeParsed: true,
      profileCompletion: 88,
      createdAt: '2026-03-10T00:00:00Z',
      updatedAt: '2026-09-15T00:00:00Z',
    },
    {
      id: 'prof-2',
      userId: DEMO_IDS.candidate2,
      headline: 'Frontend Engineer | React Specialist',
      summary: 'Creative frontend developer with 2 years of experience building beautiful, performant user interfaces with React and TypeScript.',
      phone: '+91-9876543211',
      location: 'Mumbai, India',
      skills: ['React', 'TypeScript', 'JavaScript', 'CSS', 'Tailwind CSS', 'Redux', 'Next.js', 'Jest', 'Figma'],
      experience: [
        {
          id: 'exp-3',
          title: 'Frontend Developer',
          company: 'DesignTech',
          location: 'Mumbai',
          startDate: '2024-06-01',
          endDate: '',
          current: true,
          description: 'Leading frontend development for SaaS dashboard. Built component library with 50+ reusable components. Improved page load time by 40%.',
        },
      ],
      education: [
        {
          id: 'edu-2',
          degree: 'B.E.',
          field: 'Information Technology',
          institution: 'Mumbai University',
          startDate: '2019-07-01',
          endDate: '2023-06-30',
          grade: '8.2 CGPA',
        },
      ],
      projects: [
        {
          id: 'proj-2',
          name: 'Dashboard UI Kit',
          description: 'Open-source React component library with 50+ accessible components, dark mode support, and responsive design.',
          technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Storybook'],
        },
      ],
      certifications: [],
      technologies: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Redux', 'Jest'],
      resumeParsed: true,
      profileCompletion: 75,
      createdAt: '2026-03-12T00:00:00Z',
      updatedAt: '2026-09-14T00:00:00Z',
    },
    {
      id: 'prof-3',
      userId: DEMO_IDS.candidate3,
      headline: 'Java Developer',
      summary: 'Backend developer with 1.5 years of experience in Java and Spring Framework. Looking for growth opportunities in enterprise software development.',
      location: 'Delhi, India',
      skills: ['Java', 'Spring Boot', 'SQL', 'Git', 'Maven'],
      experience: [
        {
          id: 'exp-4',
          title: 'Associate Developer',
          company: 'InfoSystems',
          location: 'Noida',
          startDate: '2025-01-01',
          endDate: '',
          current: true,
          description: 'Working on internal tools using Java and Spring Boot. Writing SQL queries for reporting dashboards.',
        },
      ],
      education: [
        {
          id: 'edu-3',
          degree: 'B.Tech',
          field: 'Computer Science',
          institution: 'DTU Delhi',
          startDate: '2020-07-01',
          endDate: '2024-06-30',
          grade: '7.8 CGPA',
        },
      ],
      projects: [],
      certifications: [],
      technologies: ['Java', 'Spring Boot', 'MySQL', 'Git'],
      resumeParsed: true,
      profileCompletion: 63,
      createdAt: '2026-03-15T00:00:00Z',
      updatedAt: '2026-09-10T00:00:00Z',
    },
  ];

  const applications: Application[] = [
    {
      id: 'APP-A1C1JB1',
      jobId: DEMO_IDS.jobA1,
      candidateId: DEMO_IDS.candidate1,
      companyId: DEMO_IDS.companyA,
      status: 'INTERVIEW',
      appliedAt: '2026-09-01T10:00:00Z',
      updatedAt: '2026-09-15T00:00:00Z',
      statusHistory: [
        { status: 'APPLIED', timestamp: '2026-09-01T10:00:00Z' },
        { status: 'SCREENING', timestamp: '2026-09-02T08:00:00Z' },
        { status: 'REVIEW', timestamp: '2026-09-03T10:00:00Z' },
        { status: 'SHORTLISTED', timestamp: '2026-09-05T14:00:00Z', changedBy: DEMO_IDS.bhrA },
        { status: 'INTERVIEW', timestamp: '2026-09-10T09:00:00Z', changedBy: DEMO_IDS.bhrA },
      ],
    },
    {
      id: 'APP-A2C1JB1',
      jobId: DEMO_IDS.jobA1,
      candidateId: DEMO_IDS.candidate3,
      companyId: DEMO_IDS.companyA,
      status: 'REVIEW',
      appliedAt: '2026-09-05T11:00:00Z',
      updatedAt: '2026-09-12T00:00:00Z',
      statusHistory: [
        { status: 'APPLIED', timestamp: '2026-09-05T11:00:00Z' },
        { status: 'SCREENING', timestamp: '2026-09-06T08:00:00Z' },
        { status: 'REVIEW', timestamp: '2026-09-08T10:00:00Z' },
      ],
    },
    {
      id: 'APP-A3C2JB2',
      jobId: DEMO_IDS.jobA2,
      candidateId: DEMO_IDS.candidate2,
      companyId: DEMO_IDS.companyA,
      status: 'SHORTLISTED',
      appliedAt: '2026-09-08T09:00:00Z',
      updatedAt: '2026-09-14T00:00:00Z',
      statusHistory: [
        { status: 'APPLIED', timestamp: '2026-09-08T09:00:00Z' },
        { status: 'SCREENING', timestamp: '2026-09-09T08:00:00Z' },
        { status: 'REVIEW', timestamp: '2026-09-10T10:00:00Z' },
        { status: 'SHORTLISTED', timestamp: '2026-09-12T14:00:00Z', changedBy: DEMO_IDS.bhrA },
      ],
    },
  ];

  const candidateMatches: CandidateMatch[] = [
    {
      id: 'match-1',
      jobId: DEMO_IDS.jobA1,
      candidateId: DEMO_IDS.candidate1,
      applicationId: 'APP-A1C1JB1',
      overallScore: 91,
      strongMatches: [
        { requirement: 'Java', status: 'FOUND', evidence: '3 years of Java experience at TechCorp India', confidence: 0.95 },
        { requirement: 'Spring Boot', status: 'FOUND', evidence: 'Developed RESTful APIs using Spring Boot', confidence: 0.93 },
        { requirement: 'SQL / PostgreSQL', status: 'FOUND', evidence: 'Managed PostgreSQL databases', confidence: 0.90 },
        { requirement: 'REST API Development', status: 'MATCHED', evidence: 'Built microservices serving 10K+ requests/minute', confidence: 0.88 },
        { requirement: '2+ years experience', status: 'FOUND', evidence: '3 years of total experience', confidence: 0.95 },
        { requirement: 'Docker / Kubernetes', status: 'FOUND', evidence: 'Implemented CI/CD pipelines with Docker', confidence: 0.80 },
      ],
      potentialGaps: [
        { requirement: 'AWS / Cloud', status: 'PARTIAL', evidence: 'AWS Cloud Practitioner certification found, but limited hands-on experience mentioned', confidence: 0.55 },
      ],
      explanation: 'Strong candidate with solid Java and Spring Boot experience. Covers all mandatory requirements with evidence from current role at TechCorp India. Has Docker experience as a preferred skill. Partial AWS exposure through certification.',
      evidenceSummary: 'Matched 6/7 requirements with high confidence. 1 partial match on AWS cloud experience.',
      createdAt: '2026-09-02T08:30:00Z',
    },
    {
      id: 'match-2',
      jobId: DEMO_IDS.jobA1,
      candidateId: DEMO_IDS.candidate3,
      applicationId: 'APP-A2C1JB1',
      overallScore: 72,
      strongMatches: [
        { requirement: 'Java', status: 'FOUND', evidence: 'Working with Java at InfoSystems', confidence: 0.85 },
        { requirement: 'Spring Boot', status: 'FOUND', evidence: 'Using Spring Boot for internal tools', confidence: 0.80 },
        { requirement: 'SQL / PostgreSQL', status: 'MATCHED', evidence: 'Writing SQL queries for reporting', confidence: 0.75 },
      ],
      potentialGaps: [
        { requirement: 'REST API Development', status: 'NOT_FOUND', evidence: 'No explicit REST API experience mentioned', confidence: 0.30 },
        { requirement: '2+ years experience', status: 'PARTIAL', evidence: '1.5 years experience — slightly below requirement', confidence: 0.60 },
        { requirement: 'Docker / Kubernetes', status: 'NOT_FOUND', confidence: 0.10 },
        { requirement: 'AWS / Cloud', status: 'NOT_FOUND', confidence: 0.10 },
      ],
      explanation: 'Has Java and Spring Boot fundamentals but lacks REST API and cloud experience. Experience is slightly below the 2-year requirement. No Docker or AWS exposure found.',
      evidenceSummary: 'Matched 3/7 requirements. 4 gaps identified, 2 critical.',
      createdAt: '2026-09-06T08:30:00Z',
    },
    {
      id: 'match-3',
      jobId: DEMO_IDS.jobA2,
      candidateId: DEMO_IDS.candidate2,
      applicationId: 'APP-A3C2JB2',
      overallScore: 87,
      strongMatches: [
        { requirement: 'React', status: 'FOUND', evidence: 'Leading frontend development, built 50+ component library', confidence: 0.95 },
        { requirement: 'TypeScript', status: 'FOUND', evidence: 'Uses TypeScript in current role and open-source projects', confidence: 0.92 },
        { requirement: 'CSS / Tailwind', status: 'FOUND', evidence: 'Tailwind CSS listed in skills and project technologies', confidence: 0.90 },
        { requirement: 'State Management', status: 'FOUND', evidence: 'Redux listed in skills', confidence: 0.85 },
        { requirement: '1+ year experience', status: 'FOUND', evidence: '2+ years of frontend development experience', confidence: 0.95 },
        { requirement: 'Testing (Jest/RTL)', status: 'FOUND', evidence: 'Jest listed in skills', confidence: 0.80 },
      ],
      potentialGaps: [],
      explanation: 'Excellent frontend candidate with strong React and TypeScript skills. Covers all requirements including preferred ones. Current role involves leading frontend development with focus on component architecture.',
      evidenceSummary: 'Matched 6/6 requirements with high confidence. No gaps identified.',
      createdAt: '2026-09-09T08:30:00Z',
    },
  ];

  const interviews: Interview[] = [
    {
      id: 'int-1',
      applicationId: 'APP-A1C1JB1',
      jobId: DEMO_IDS.jobA1,
      candidateId: DEMO_IDS.candidate1,
      interviewerId: DEMO_IDS.interviewerA1,
      companyId: DEMO_IDS.companyA,
      stage: 'Technical Round',
      scheduledDate: '2026-09-20',
      scheduledTime: '10:00',
      duration: 60,
      meetingLink: 'https://meet.google.com/abc-defg-hij',
      status: 'scheduled',
      createdAt: '2026-09-12T00:00:00Z',
      updatedAt: '2026-09-12T00:00:00Z',
    },
  ];

  const notifications: Notification[] = [
    {
      id: 'notif-1',
      userId: DEMO_IDS.bhrA,
      type: 'new_application',
      title: 'New Application',
      message: 'Arjun Mehta applied for Backend Developer',
      read: false,
      link: '/company/jobs/job-backend-dev',
      createdAt: '2026-09-01T10:00:00Z',
    },
    {
      id: 'notif-2',
      userId: DEMO_IDS.bhrA,
      type: 'new_application',
      title: 'New Application',
      message: 'Rohit Verma applied for Backend Developer',
      read: false,
      link: '/company/jobs/job-backend-dev',
      createdAt: '2026-09-05T11:00:00Z',
    },
    {
      id: 'notif-3',
      userId: DEMO_IDS.candidate1,
      type: 'interview_scheduled',
      title: 'Interview Invitation',
      message: 'Your interview for Backend Developer at Alpha Technologies has been scheduled',
      read: false,
      link: '/candidate/interviews',
      createdAt: '2026-09-12T00:00:00Z',
    },
    {
      id: 'notif-4',
      userId: DEMO_IDS.interviewerA1,
      type: 'interview_scheduled',
      title: 'Interview Assigned',
      message: 'You have been assigned to interview Arjun Mehta for Backend Developer',
      read: false,
      link: '/interviewer/interviews/int-1',
      createdAt: '2026-09-12T00:00:00Z',
    },
  ];

  return {
    users,
    companies,
    companyMembers,
    jobs,
    applications,
    candidateProfiles,
    candidateMatches,
    interviews,
    notifications,
  };
}
