import type { User, Company, CompanyMember } from "../types";
import { DEMO_IDS, daysAgo } from "./seedHelpers";

export const users: User[] = [
  { id: DEMO_IDS.admin, email: "demo-admin@hireflow.com", displayName: "Admin User", role: "PLATFORM_ADMIN", status: "active", createdAt: daysAgo(270), updatedAt: daysAgo(270) },
  { id: DEMO_IDS.bhrA, email: "demo-bhr@example.com", displayName: "Rajesh Kumar", role: "BHR_MANAGER", companyId: DEMO_IDS.companyA, status: "active", createdAt: daysAgo(260), updatedAt: daysAgo(260) },
  { id: DEMO_IDS.hrA, email: "demo-hr@example.com", displayName: "Anita Desai", role: "HR_RECRUITER", companyId: DEMO_IDS.companyA, status: "active", createdAt: daysAgo(245), updatedAt: daysAgo(245) },
  { id: DEMO_IDS.hrA2, email: "hr2-alpha@example.com", displayName: "Kavitha Rao", role: "HR_RECRUITER", companyId: DEMO_IDS.companyA, status: "active", createdAt: daysAgo(240), updatedAt: daysAgo(240) },
  { id: DEMO_IDS.interviewerA1, email: "demo-interviewer@example.com", displayName: "Vikram Singh", role: "INTERVIEWER", companyId: DEMO_IDS.companyA, status: "active", createdAt: daysAgo(230), updatedAt: daysAgo(230) },
  { id: DEMO_IDS.interviewerA2, email: "interviewer2@example.com", displayName: "Sneha Patel", role: "INTERVIEWER", companyId: DEMO_IDS.companyA, status: "active", createdAt: daysAgo(230), updatedAt: daysAgo(230) },
  { id: DEMO_IDS.interviewerA3, email: "interviewer3@example.com", displayName: "Arun Nair", role: "INTERVIEWER", companyId: DEMO_IDS.companyA, status: "active", createdAt: daysAgo(220), updatedAt: daysAgo(220) },
  { id: DEMO_IDS.interviewerA4, email: "interviewer4@example.com", displayName: "Deepa Menon", role: "INTERVIEWER", companyId: DEMO_IDS.companyA, status: "active", createdAt: daysAgo(220), updatedAt: daysAgo(220) },
  { id: DEMO_IDS.interviewerA5, email: "interviewer5@example.com", displayName: "Sanjay Gupta", role: "INTERVIEWER", companyId: DEMO_IDS.companyA, status: "active", createdAt: daysAgo(210), updatedAt: daysAgo(210) },
  { id: DEMO_IDS.interviewerA6, email: "interviewer6@example.com", displayName: "Ritu Sharma", role: "INTERVIEWER", companyId: DEMO_IDS.companyA, status: "active", createdAt: daysAgo(210), updatedAt: daysAgo(210) },
  { id: DEMO_IDS.bhrB, email: "bhr-beta@example.com", displayName: "Meera Nair", role: "BHR_MANAGER", companyId: DEMO_IDS.companyB, status: "active", createdAt: daysAgo(200), updatedAt: daysAgo(200) },
  { id: DEMO_IDS.hrB, email: "hr-beta@example.com", displayName: "Kiran Babu", role: "HR_RECRUITER", companyId: DEMO_IDS.companyB, status: "active", createdAt: daysAgo(195), updatedAt: daysAgo(195) },
  { id: DEMO_IDS.interviewerB1, email: "int-beta1@example.com", displayName: "Suresh Pillai", role: "INTERVIEWER", companyId: DEMO_IDS.companyB, status: "active", createdAt: daysAgo(190), updatedAt: daysAgo(190) },
  { id: DEMO_IDS.bhrC, email: "bhr-gamma@example.com", displayName: "Preethi Iyer", role: "BHR_MANAGER", companyId: DEMO_IDS.companyC, status: "active", createdAt: daysAgo(150), updatedAt: daysAgo(150) },
  { id: DEMO_IDS.interviewerC1, email: "int-gamma1@example.com", displayName: "Nikhil Joshi", role: "INTERVIEWER", companyId: DEMO_IDS.companyC, status: "active", createdAt: daysAgo(145), updatedAt: daysAgo(145) },
  { id: DEMO_IDS.candidate1, email: "demo-candidate@example.com", displayName: "Arjun Mehta", role: "CANDIDATE", status: "active", createdAt: daysAgo(200), updatedAt: daysAgo(200) },
  { id: DEMO_IDS.candidate2, email: "candidate2@example.com", displayName: "Priya Sharma", role: "CANDIDATE", status: "active", createdAt: daysAgo(195), updatedAt: daysAgo(195) },
  { id: DEMO_IDS.candidate3, email: "candidate3@example.com", displayName: "Rohit Verma", role: "CANDIDATE", status: "active", createdAt: daysAgo(190), updatedAt: daysAgo(190) },
  { id: DEMO_IDS.candidate4, email: "candidate4@example.com", displayName: "Pooja Krishnan", role: "CANDIDATE", status: "active", createdAt: daysAgo(185), updatedAt: daysAgo(185) },
  { id: DEMO_IDS.candidate5, email: "candidate5@example.com", displayName: "Suresh Babu", role: "CANDIDATE", status: "active", createdAt: daysAgo(180), updatedAt: daysAgo(180) },
  { id: DEMO_IDS.candidate6, email: "candidate6@example.com", displayName: "Nisha Agarwal", role: "CANDIDATE", status: "active", createdAt: daysAgo(175), updatedAt: daysAgo(175) },
  { id: DEMO_IDS.candidate7, email: "candidate7@example.com", displayName: "Aman Tiwari", role: "CANDIDATE", status: "active", createdAt: daysAgo(170), updatedAt: daysAgo(170) },
  { id: DEMO_IDS.candidate8, email: "candidate8@example.com", displayName: "Divya Pillai", role: "CANDIDATE", status: "active", createdAt: daysAgo(165), updatedAt: daysAgo(165) },
  { id: DEMO_IDS.candidate9, email: "candidate9@example.com", displayName: "Ravi Chandran", role: "CANDIDATE", status: "active", createdAt: daysAgo(160), updatedAt: daysAgo(160) },
  { id: DEMO_IDS.candidate10, email: "candidate10@example.com", displayName: "Swati Jain", role: "CANDIDATE", status: "active", createdAt: daysAgo(155), updatedAt: daysAgo(155) },
  { id: DEMO_IDS.candidate11, email: "candidate11@example.com", displayName: "Karthik Reddy", role: "CANDIDATE", status: "active", createdAt: daysAgo(150), updatedAt: daysAgo(150) },
  { id: DEMO_IDS.candidate12, email: "candidate12@example.com", displayName: "Meghana Singh", role: "CANDIDATE", status: "active", createdAt: daysAgo(145), updatedAt: daysAgo(145) },
  { id: DEMO_IDS.candidate13, email: "candidate13@example.com", displayName: "Ajay Kulkarni", role: "CANDIDATE", status: "active", createdAt: daysAgo(140), updatedAt: daysAgo(140) },
  { id: DEMO_IDS.candidate14, email: "candidate14@example.com", displayName: "Lakshmi Devi", role: "CANDIDATE", status: "active", createdAt: daysAgo(135), updatedAt: daysAgo(135) },
  { id: DEMO_IDS.candidate15, email: "candidate15@example.com", displayName: "Varun Kapoor", role: "CANDIDATE", status: "active", createdAt: daysAgo(130), updatedAt: daysAgo(130) },
  { id: DEMO_IDS.candidate16, email: "candidate16@example.com", displayName: "Ananya Roy", role: "CANDIDATE", status: "active", createdAt: daysAgo(125), updatedAt: daysAgo(125) },
  { id: DEMO_IDS.candidate17, email: "candidate17@example.com", displayName: "Rahul Bose", role: "CANDIDATE", status: "active", createdAt: daysAgo(120), updatedAt: daysAgo(120) },
  { id: DEMO_IDS.candidate18, email: "candidate18@example.com", displayName: "Shreya Menon", role: "CANDIDATE", status: "active", createdAt: daysAgo(115), updatedAt: daysAgo(115) },
  { id: DEMO_IDS.candidate19, email: "candidate19@example.com", displayName: "Deepak Pandey", role: "CANDIDATE", status: "active", createdAt: daysAgo(110), updatedAt: daysAgo(110) },
  { id: DEMO_IDS.candidate20, email: "candidate20@example.com", displayName: "Tanvi Deshmukh", role: "CANDIDATE", status: "active", createdAt: daysAgo(105), updatedAt: daysAgo(105) },
];

export const companies: Company[] = [
  {
    id: DEMO_IDS.companyA, name: "Alpha Technologies",
    description: "A leading software development company specializing in cloud-native enterprise solutions.",
    industry: "Information Technology", website: "https://alphatech.example.com",
    location: "Bangalore, India", size: "200-500", foundedYear: 2018, headquarters: "Bangalore, Karnataka",
    departments: ["Engineering", "Data", "DevOps/Cloud", "QA", "Product", "Design", "HR", "Sales"],
    techStack: ["Java", "Spring Boot", "React", "TypeScript", "AWS", "Kubernetes", "PostgreSQL", "Kafka"],
    hiringLocations: ["Bangalore", "Hyderabad", "Pune", "Remote (India)"], workModePolicy: "hybrid",
    interviewStages: ["HR Screen", "Technical Round 1", "Technical Round 2", "Managerial", "Culture Fit"],
    onboardingCompleted: true, createdAt: daysAgo(260), updatedAt: daysAgo(30),
  },
  {
    id: DEMO_IDS.companyB, name: "Beta Solutions",
    description: "Data analytics and business intelligence company providing end-to-end data solutions.",
    industry: "Data Analytics", website: "https://betasolutions.example.com",
    location: "Hyderabad, India", size: "50-200", foundedYear: 2020, headquarters: "Hyderabad, Telangana",
    departments: ["Data Platform", "Analytics", "Engineering", "HR"],
    techStack: ["Python", "Apache Spark", "Airflow", "BigQuery", "dbt", "Tableau", "PostgreSQL"],
    hiringLocations: ["Hyderabad", "Chennai", "Remote (India)"], workModePolicy: "hybrid",
    interviewStages: ["HR Screen", "Technical Assessment", "Technical Round", "Managerial"],
    onboardingCompleted: true, createdAt: daysAgo(200), updatedAt: daysAgo(20),
  },
  {
    id: DEMO_IDS.companyC, name: "Gamma Systems",
    description: "An early-stage SaaS startup building next-generation DevOps tooling.",
    industry: "SaaS / DevOps", website: "https://gammasystems.example.com",
    location: "Pune, India", size: "10-50", foundedYear: 2024, headquarters: "Pune, Maharashtra",
    departments: ["Engineering", "DevOps", "Product"],
    techStack: ["Go", "Kubernetes", "Terraform", "React", "PostgreSQL", "AWS"],
    hiringLocations: ["Pune", "Remote (India)"], workModePolicy: "remote",
    interviewStages: ["Founder Call", "Technical Round", "Pair Programming"],
    onboardingCompleted: true, createdAt: daysAgo(150), updatedAt: daysAgo(10),
  },
];

export const companyMembers: CompanyMember[] = [
  { id: "mem-1", userId: DEMO_IDS.bhrA, companyId: DEMO_IDS.companyA, role: "BHR_MANAGER", permissions: ["all"], joinedAt: daysAgo(260) },
  { id: "mem-2", userId: DEMO_IDS.hrA, companyId: DEMO_IDS.companyA, role: "HR_RECRUITER", permissions: ["view_jobs","view_applications","manage_candidates","schedule_interviews"], joinedAt: daysAgo(245) },
  { id: "mem-2b", userId: DEMO_IDS.hrA2, companyId: DEMO_IDS.companyA, role: "HR_RECRUITER", permissions: ["view_jobs","view_applications","manage_candidates","schedule_interviews"], joinedAt: daysAgo(240) },
  { id: "mem-3", userId: DEMO_IDS.interviewerA1, companyId: DEMO_IDS.companyA, role: "INTERVIEWER", permissions: ["view_assigned_interviews"], joinedAt: daysAgo(230) },
  { id: "mem-4", userId: DEMO_IDS.interviewerA2, companyId: DEMO_IDS.companyA, role: "INTERVIEWER", permissions: ["view_assigned_interviews"], joinedAt: daysAgo(230) },
  { id: "mem-4b", userId: DEMO_IDS.interviewerA3, companyId: DEMO_IDS.companyA, role: "INTERVIEWER", permissions: ["view_assigned_interviews"], joinedAt: daysAgo(220) },
  { id: "mem-4c", userId: DEMO_IDS.interviewerA4, companyId: DEMO_IDS.companyA, role: "INTERVIEWER", permissions: ["view_assigned_interviews"], joinedAt: daysAgo(220) },
  { id: "mem-4d", userId: DEMO_IDS.interviewerA5, companyId: DEMO_IDS.companyA, role: "INTERVIEWER", permissions: ["view_assigned_interviews"], joinedAt: daysAgo(210) },
  { id: "mem-4e", userId: DEMO_IDS.interviewerA6, companyId: DEMO_IDS.companyA, role: "INTERVIEWER", permissions: ["view_assigned_interviews"], joinedAt: daysAgo(210) },
  { id: "mem-5", userId: DEMO_IDS.bhrB, companyId: DEMO_IDS.companyB, role: "BHR_MANAGER", permissions: ["all"], joinedAt: daysAgo(200) },
  { id: "mem-5b", userId: DEMO_IDS.hrB, companyId: DEMO_IDS.companyB, role: "HR_RECRUITER", permissions: ["view_jobs","view_applications","manage_candidates","schedule_interviews"], joinedAt: daysAgo(195) },
  { id: "mem-5c", userId: DEMO_IDS.interviewerB1, companyId: DEMO_IDS.companyB, role: "INTERVIEWER", permissions: ["view_assigned_interviews"], joinedAt: daysAgo(190) },
  { id: "mem-6", userId: DEMO_IDS.bhrC, companyId: DEMO_IDS.companyC, role: "BHR_MANAGER", permissions: ["all"], joinedAt: daysAgo(150) },
  { id: "mem-6b", userId: DEMO_IDS.interviewerC1, companyId: DEMO_IDS.companyC, role: "INTERVIEWER", permissions: ["view_assigned_interviews"], joinedAt: daysAgo(145) },
];
