import type { CandidateProfile } from "../types";
import { DEMO_IDS, daysAgo } from "./seedHelpers";

export const candidateProfiles: CandidateProfile[] = [
  {
    id: "prof-1", userId: DEMO_IDS.candidate1,
    headline: "Full Stack Developer | Java & React | 3 Years",
    summary: "Passionate software developer with 3 years of experience building scalable web applications.",
    phone: "+91-9876543210", location: "Bangalore, India",
    linkedIn: "https://linkedin.com/in/arjunmehta", github: "https://github.com/arjunmehta",
    skills: ["Java", "Spring Boot", "React", "TypeScript", "PostgreSQL", "REST APIs", "Docker", "Git", "Agile"],
    experience: [
      { id: "exp-1", title: "Software Developer", company: "TechCorp India", location: "Bangalore", startDate: "2024-01-01", endDate: "", current: true, description: "Developed RESTful APIs using Spring Boot and managed PostgreSQL databases." },
      { id: "exp-2", title: "Junior Developer", company: "StartupXYZ", location: "Pune", startDate: "2023-01-01", endDate: "2023-12-31", current: false, description: "Built full-stack features using Java backend and React frontend." },
    ],
    education: [{ id: "edu-1", degree: "B.Tech", field: "Computer Science", institution: "VIT University", startDate: "2019-07-01", endDate: "2023-06-30", grade: "8.5 CGPA" }],
    projects: [{ id: "proj-1", name: "E-Commerce Platform", description: "Full-stack e-commerce with Spring Boot, React, PostgreSQL.", technologies: ["Java", "Spring Boot", "React", "PostgreSQL", "Docker"], url: "https://github.com/arjun/ecommerce" }],
    certifications: [{ id: "cert-1", name: "AWS Cloud Practitioner", issuer: "Amazon Web Services", issuedDate: "2025-06" }],
    technologies: ["Java", "Spring Boot", "React", "TypeScript", "PostgreSQL", "Docker", "AWS", "Jenkins"],
    resumeParsed: true, profileCompletion: 88,
    createdAt: daysAgo(200), updatedAt: daysAgo(19),
  },
  {
    id: "prof-2", userId: DEMO_IDS.candidate2,
    headline: "Frontend Engineer | React & TypeScript | 2 Years",
    summary: "Creative frontend developer with 2 years of experience building beautiful, performant user interfaces.",
    phone: "+91-9876543211", location: "Mumbai, India",
    skills: ["React", "TypeScript", "JavaScript", "CSS", "Tailwind CSS", "Redux", "Next.js", "Jest", "Figma"],
    experience: [{ id: "exp-3", title: "Frontend Developer", company: "DesignTech", location: "Mumbai", startDate: "2024-06-01", endDate: "", current: true, description: "Leading frontend development for SaaS dashboard." }],
    education: [{ id: "edu-2", degree: "B.E.", field: "Information Technology", institution: "Mumbai University", startDate: "2019-07-01", endDate: "2023-06-30", grade: "8.2 CGPA" }],
    projects: [{ id: "proj-2", name: "Dashboard UI Kit", description: "Open-source React component library.", technologies: ["React", "TypeScript", "Tailwind CSS", "Storybook"] }],
    certifications: [],
    technologies: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Redux", "Jest"],
    resumeParsed: true, profileCompletion: 75,
    createdAt: daysAgo(195), updatedAt: daysAgo(20),
  },
  {
    id: "prof-3", userId: DEMO_IDS.candidate3,
    headline: "Java Developer | 1.5 Years | Seeking Growth",
    summary: "Backend developer with 1.5 years of experience in Java and Spring Framework.",
    location: "Delhi, India",
    skills: ["Java", "Spring Boot", "SQL", "Git", "Maven"],
    experience: [{ id: "exp-4", title: "Associate Developer", company: "InfoSystems", location: "Noida", startDate: "2025-01-01", endDate: "", current: true, description: "Working on internal tools using Java and Spring Boot." }],
    education: [{ id: "edu-3", degree: "B.Tech", field: "Computer Science", institution: "DTU Delhi", startDate: "2020-07-01", endDate: "2024-06-30", grade: "7.8 CGPA" }],
    projects: [], certifications: [],
    technologies: ["Java", "Spring Boot", "MySQL", "Git"],
    resumeParsed: true, profileCompletion: 63,
    createdAt: daysAgo(190), updatedAt: daysAgo(24),
  },
  {
    id: "prof-4", userId: DEMO_IDS.candidate4,
    headline: "Data Engineer | Python & Spark | 5 Years | Hyderabad",
    summary: "5-year data engineer with expertise in building large-scale ETL pipelines.",
    phone: "+91-9988776655", location: "Hyderabad, India",
    skills: ["Python", "Apache Spark", "Airflow", "SQL", "BigQuery", "dbt", "PostgreSQL", "AWS S3", "Kafka"],
    experience: [
      { id: "exp-5", title: "Senior Data Engineer", company: "DataFlow Systems", location: "Hyderabad", startDate: "2023-01-01", endDate: "", current: true, description: "Leading data pipeline design for 10 TB/day data processing." },
      { id: "exp-6", title: "Data Engineer", company: "FinTech Corp", location: "Hyderabad", startDate: "2021-06-01", endDate: "2022-12-31", current: false, description: "Built ETL pipelines for loan data processing." },
    ],
    education: [{ id: "edu-4", degree: "M.Tech", field: "Data Science", institution: "IIIT Hyderabad", startDate: "2019-07-01", endDate: "2021-06-30", grade: "8.9 CGPA" }],
    projects: [{ id: "proj-4", name: "Real-time Streaming Pipeline", description: "Built Kafka + Spark Streaming pipeline.", technologies: ["Python", "Kafka", "Apache Spark", "PostgreSQL", "AWS"] }],
    certifications: [{ id: "cert-4", name: "Google Cloud Professional Data Engineer", issuer: "Google", issuedDate: "2025-03" }],
    technologies: ["Python", "Apache Spark", "Airflow", "Kafka", "BigQuery", "dbt", "AWS"],
    resumeParsed: true, profileCompletion: 95,
    createdAt: daysAgo(185), updatedAt: daysAgo(15),
  },
  {
    id: "prof-5", userId: DEMO_IDS.candidate5,
    headline: "Senior Backend Engineer | Java/Kotlin | Distributed Systems | 8 Years",
    summary: "Senior engineer with 8 years building distributed systems with Java/Kotlin.",
    phone: "+91-9876501234", location: "Pune, India",
    skills: ["Java", "Kotlin", "Spring Boot", "Kafka", "PostgreSQL", "Redis", "Kubernetes", "AWS", "gRPC", "Microservices"],
    experience: [
      { id: "exp-7", title: "Principal Engineer", company: "Infosys Digital", location: "Pune", startDate: "2022-06-01", endDate: "", current: true, description: "Leading architecture of payment processing microservices." },
      { id: "exp-8", title: "Senior Software Engineer", company: "Persistent Systems", location: "Pune", startDate: "2019-01-01", endDate: "2022-05-31", current: false, description: "Built distributed caching layer with Redis." },
    ],
    education: [{ id: "edu-5", degree: "B.E.", field: "Computer Engineering", institution: "COEP Pune", startDate: "2014-07-01", endDate: "2018-06-30", grade: "8.7 CGPA" }],
    projects: [],
    certifications: [{ id: "cert-5", name: "AWS Solutions Architect – Professional", issuer: "Amazon Web Services", issuedDate: "2024-11" }],
    technologies: ["Java", "Kotlin", "Kafka", "Kubernetes", "PostgreSQL", "Redis", "AWS", "gRPC"],
    resumeParsed: true, profileCompletion: 90,
    createdAt: daysAgo(180), updatedAt: daysAgo(12),
  },
  {
    id: "prof-6", userId: DEMO_IDS.candidate6,
    headline: "QA Automation Engineer | Selenium & Playwright | 2 Years",
    summary: "QA engineer with 2 years of experience writing automation frameworks.",
    phone: "+91-9811223344", location: "Bangalore, India",
    skills: ["Selenium", "Playwright", "Java", "Python", "Postman", "RestAssured", "TestNG", "CI/CD", "Git"],
    experience: [{ id: "exp-9", title: "QA Engineer", company: "QualTest Labs", location: "Bangalore", startDate: "2024-07-01", endDate: "", current: true, description: "Maintaining 3,000+ automated test cases with Playwright." }],
    education: [{ id: "edu-6", degree: "B.Sc", field: "Computer Science", institution: "Bangalore University", startDate: "2021-07-01", endDate: "2024-05-30", grade: "7.5 CGPA" }],
    projects: [{ id: "proj-6", name: "API Test Framework", description: "Built reusable RestAssured test framework.", technologies: ["Java", "RestAssured", "TestNG", "Maven"] }],
    certifications: [],
    technologies: ["Selenium", "Playwright", "Java", "RestAssured", "TestNG", "GitHub Actions"],
    resumeParsed: true, profileCompletion: 78,
    createdAt: daysAgo(175), updatedAt: daysAgo(18),
  },
  {
    id: "prof-7", userId: DEMO_IDS.candidate7,
    headline: "ML Engineer | Python & PyTorch | 1 Year",
    summary: "ML engineer with 1 year of experience in training NLP models using PyTorch.",
    location: "Bangalore, India",
    skills: ["Python", "PyTorch", "HuggingFace", "Scikit-learn", "FastAPI", "Docker", "Git"],
    experience: [{ id: "exp-10", title: "ML Engineer", company: "AI Startup (YC S25)", location: "Bangalore", startDate: "2025-07-01", endDate: "", current: true, description: "Fine-tuning LLaMA 3 for customer support chatbot." }],
    education: [{ id: "edu-7", degree: "B.Tech", field: "AI & ML", institution: "BITS Pilani", startDate: "2020-07-01", endDate: "2024-06-30", grade: "9.1 CGPA" }],
    projects: [{ id: "proj-7", name: "LLM Fine-tuning for Legal Text", description: "Fine-tuned Mistral-7B on 50K legal documents.", technologies: ["Python", "PyTorch", "HuggingFace", "PEFT", "LoRA"] }],
    certifications: [],
    technologies: ["Python", "PyTorch", "HuggingFace", "FastAPI", "Docker"],
    resumeParsed: true, profileCompletion: 72,
    createdAt: daysAgo(170), updatedAt: daysAgo(22),
  },
  {
    id: "prof-8", userId: DEMO_IDS.candidate8,
    headline: "Senior Frontend Engineer | React | TypeScript | 4 Years",
    summary: "Senior frontend engineer with 4 years at product companies. Built design systems.",
    phone: "+91-9944332211", location: "Hyderabad, India",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Redux Toolkit", "Jest", "Cypress", "Figma", "D3.js", "CSS Modules"],
    experience: [
      { id: "exp-11", title: "Senior Frontend Engineer", company: "Sharechat", location: "Bangalore", startDate: "2022-09-01", endDate: "", current: true, description: "Leading frontend of creator analytics dashboard." },
      { id: "exp-12", title: "Frontend Developer", company: "ZestMoney", location: "Bangalore", startDate: "2021-06-01", endDate: "2022-08-31", current: false, description: "Built React loan application flow." },
    ],
    education: [{ id: "edu-8", degree: "B.Tech", field: "IT", institution: "NIT Trichy", startDate: "2017-07-01", endDate: "2021-06-30", grade: "8.8 CGPA" }],
    projects: [], certifications: [],
    technologies: ["React", "TypeScript", "Next.js", "GraphQL", "D3.js", "Cypress"],
    resumeParsed: true, profileCompletion: 85,
    createdAt: daysAgo(165), updatedAt: daysAgo(14),
  },
  {
    id: "prof-9", userId: DEMO_IDS.candidate9,
    headline: "DevOps Engineer | Kubernetes & Terraform | 3 Years | Hyderabad",
    summary: "3-year DevOps engineer with strong hands-on experience managing EKS clusters.",
    phone: "+91-9900112233", location: "Hyderabad, India",
    skills: ["Kubernetes", "Terraform", "AWS", "Docker", "GitHub Actions", "Helm", "Prometheus", "Grafana", "Python", "Bash"],
    experience: [{ id: "exp-13", title: "DevOps Engineer", company: "CloudEdge Technologies", location: "Hyderabad", startDate: "2023-08-01", endDate: "", current: true, description: "Managing 15-node EKS cluster across 3 environments." }],
    education: [{ id: "edu-9", degree: "B.Tech", field: "Computer Science", institution: "JNTU Hyderabad", startDate: "2019-07-01", endDate: "2023-06-30", grade: "7.9 CGPA" }],
    projects: [{ id: "proj-9", name: "Zero-downtime Deployment Framework", description: "Built GitOps pipeline with ArgoCD.", technologies: ["Kubernetes", "ArgoCD", "Helm", "Terraform", "GitHub Actions"] }],
    certifications: [{ id: "cert-9", name: "Certified Kubernetes Administrator (CKA)", issuer: "CNCF", issuedDate: "2024-08" }],
    technologies: ["Kubernetes", "Terraform", "AWS", "Helm", "ArgoCD", "Prometheus", "Grafana"],
    resumeParsed: true, profileCompletion: 88,
    createdAt: daysAgo(160), updatedAt: daysAgo(16),
  },
  {
    id: "prof-10", userId: DEMO_IDS.candidate10,
    headline: "Final Year B.Tech CS | Java & React | Seeking Internship",
    summary: "Final-year Computer Science student with strong fundamentals in Java and React.",
    location: "Pune, India",
    skills: ["Java", "Spring Boot", "React", "SQL", "Git", "Python basics"],
    experience: [{ id: "exp-14", title: "Web Development Intern", company: "CodeCraft (NGO)", location: "Remote", startDate: "2026-05-01", endDate: "2026-07-31", current: false, description: "Built a React + Node.js volunteer management platform." }],
    education: [{ id: "edu-10", degree: "B.Tech", field: "Computer Science", institution: "Pune University (COEP)", startDate: "2022-07-01", endDate: "2026-06-30", grade: "8.3 CGPA" }],
    projects: [{ id: "proj-10", name: "Hospital Appointment System", description: "Spring Boot + React app for hospital appointment management.", technologies: ["Java", "Spring Boot", "React", "MySQL"] }],
    certifications: [], technologies: ["Java", "Spring Boot", "React", "MySQL", "Git"],
    resumeParsed: true, profileCompletion: 68, createdAt: daysAgo(155), updatedAt: daysAgo(20),
  },
  {
    id: "prof-11", userId: DEMO_IDS.candidate11,
    headline: "Data Engineer | Python & dbt | 6 Years | Bangalore",
    summary: "6-year data engineer specialising in dbt, BigQuery, and Airflow.",
    phone: "+91-9966554433", location: "Bangalore, India",
    skills: ["Python", "dbt", "BigQuery", "Airflow", "SQL", "Apache Spark", "GCP", "Kafka"],
    experience: [
      { id: "exp-15", title: "Lead Data Engineer", company: "PhonePe", location: "Bangalore", startDate: "2022-10-01", endDate: "", current: true, description: "Leading data platform for payments analytics processing 1B+ transactions/month." },
      { id: "exp-16", title: "Data Engineer", company: "Freshworks", location: "Chennai", startDate: "2020-07-01", endDate: "2022-09-30", current: false, description: "Built ETL pipelines for CRM analytics in BigQuery." },
    ],
    education: [{ id: "edu-11", degree: "B.Tech", field: "Computer Science", institution: "IIT Madras", startDate: "2016-07-01", endDate: "2020-06-30", grade: "8.4 CGPA" }],
    projects: [], certifications: [{ id: "cert-11", name: "dbt Certified Developer", issuer: "dbt Labs", issuedDate: "2025-01" }],
    technologies: ["Python", "dbt", "BigQuery", "Airflow", "Kafka", "GCP", "Spark"],
    resumeParsed: true, profileCompletion: 92, createdAt: daysAgo(150), updatedAt: daysAgo(10),
  },
  {
    id: "prof-12", userId: DEMO_IDS.candidate12,
    headline: "Product Analyst | SQL & Tableau | Career Switcher from Business",
    summary: "4 years in business operations + 1 year in product analytics.",
    location: "Bangalore, India",
    skills: ["SQL", "Tableau", "Excel", "Python (basics)", "Product Metrics", "A/B Testing", "Mixpanel"],
    experience: [
      { id: "exp-17", title: "Product Analyst", company: "Urban Company", location: "Bangalore", startDate: "2025-09-01", endDate: "", current: true, description: "Tracking retention and conversion funnels. Built Tableau dashboard." },
      { id: "exp-18", title: "Business Analyst", company: "Deloitte", location: "Bangalore", startDate: "2022-06-01", endDate: "2025-08-31", current: false, description: "Managed process improvement projects for 3 BFSI clients." },
    ],
    education: [{ id: "edu-12", degree: "MBA", field: "Business Analytics", institution: "IIM Kozhikode", startDate: "2020-07-01", endDate: "2022-05-31", grade: "A-" }],
    projects: [{ id: "proj-12", name: "Retention Dashboard", description: "D30/D90 retention Tableau dashboard.", technologies: ["Tableau", "SQL", "BigQuery"] }],
    certifications: [], technologies: ["SQL", "Tableau", "Mixpanel", "Python", "BigQuery"],
    resumeParsed: true, profileCompletion: 80, createdAt: daysAgo(145), updatedAt: daysAgo(8),
  },
  {
    id: "prof-13", userId: DEMO_IDS.candidate13,
    headline: "Backend Engineer | Go & gRPC | 4 Years | Pune",
    summary: "4-year backend engineer with a focus on Go and high-performance API services.",
    phone: "+91-9812345678", location: "Pune, India",
    skills: ["Go", "gRPC", "PostgreSQL", "Redis", "Kafka", "Kubernetes", "AWS", "Terraform"],
    experience: [{ id: "exp-19", title: "Software Engineer II", company: "Razorpay", location: "Bangalore", startDate: "2022-08-01", endDate: "", current: true, description: "Built payment settlement Go service processing ₹200 Cr/day." }],
    education: [{ id: "edu-13", degree: "B.E.", field: "Computer Engineering", institution: "COEP Pune", startDate: "2018-07-01", endDate: "2022-06-30", grade: "8.6 CGPA" }],
    projects: [], certifications: [{ id: "cert-13", name: "CKA (Certified Kubernetes Administrator)", issuer: "CNCF", issuedDate: "2024-06" }],
    technologies: ["Go", "gRPC", "PostgreSQL", "Redis", "Kafka", "Kubernetes", "Terraform"],
    resumeParsed: true, profileCompletion: 88, createdAt: daysAgo(140), updatedAt: daysAgo(11),
  },
  {
    id: "prof-14", userId: DEMO_IDS.candidate14,
    headline: "Python Developer | FastAPI & PostgreSQL | 2 Years | Chennai",
    summary: "Backend Python developer with 2 years experience building FastAPI microservices.",
    location: "Chennai, India",
    skills: ["Python", "FastAPI", "PostgreSQL", "SQLAlchemy", "Docker", "Redis", "Celery", "Git"],
    experience: [{ id: "exp-20", title: "Python Developer", company: "Agilisium Consulting", location: "Chennai", startDate: "2024-08-01", endDate: "", current: true, description: "Building data ingestion microservices in FastAPI for healthcare clients." }],
    education: [{ id: "edu-14", degree: "B.Tech", field: "Information Technology", institution: "Anna University", startDate: "2020-07-01", endDate: "2024-05-31", grade: "8.1 CGPA" }],
    projects: [{ id: "proj-14", name: "Clinical Data API", description: "FastAPI service for clinical trial data ingestion.", technologies: ["Python", "FastAPI", "PostgreSQL", "Celery", "Redis", "Docker"] }],
    certifications: [], technologies: ["Python", "FastAPI", "PostgreSQL", "Celery", "Redis", "Docker"],
    resumeParsed: true, profileCompletion: 75, createdAt: daysAgo(135), updatedAt: daysAgo(9),
  },
  {
    id: "prof-15", userId: DEMO_IDS.candidate15,
    headline: "BI Analyst | Power BI & SQL | 1 Year | Gurugram",
    summary: "BI analyst with 1 year building Power BI reports and writing DAX measures.",
    location: "Gurugram, India",
    skills: ["Power BI", "DAX", "SQL", "Excel", "Azure Data Factory", "Python basics"],
    experience: [{ id: "exp-21", title: "BI Analyst", company: "Capgemini India", location: "Gurugram", startDate: "2025-07-01", endDate: "", current: true, description: "Building Power BI executive dashboards for 3 BFSI clients." }],
    education: [{ id: "edu-15", degree: "B.Com", field: "Finance & Analytics", institution: "Shri Ram College of Commerce (DU)", startDate: "2022-07-01", endDate: "2025-06-30", grade: "8.0 CGPA" }],
    projects: [], certifications: [{ id: "cert-15", name: "Microsoft Power BI Data Analyst (PL-300)", issuer: "Microsoft", issuedDate: "2025-10" }],
    technologies: ["Power BI", "DAX", "SQL", "Azure Data Factory"],
    resumeParsed: false, profileCompletion: 60, createdAt: daysAgo(130), updatedAt: daysAgo(7),
  },
  {
    id: "prof-16", userId: DEMO_IDS.candidate16,
    headline: "React Developer | Final Year | Campus Hire | Kolkata",
    summary: "Final-year CS student with strong React skills. Interned at a startup for 2 months.",
    location: "Kolkata, India",
    skills: ["React", "JavaScript", "HTML", "CSS", "Git", "Node.js basics"],
    experience: [{ id: "exp-22", title: "Frontend Intern", company: "Codezilla Startup", location: "Remote", startDate: "2026-06-01", endDate: "2026-07-31", current: false, description: "Built 3 React components for B2B SaaS dashboard." }],
    education: [{ id: "edu-16", degree: "B.Tech", field: "CSE", institution: "Jadavpur University", startDate: "2022-07-01", endDate: "2026-06-30", grade: "8.6 CGPA" }],
    projects: [{ id: "proj-16", name: "Portfolio + Blog", description: "Personal portfolio built with React.", technologies: ["React", "JavaScript", "Vercel", "Tailwind CSS"] }],
    certifications: [], technologies: ["React", "JavaScript", "Node.js", "Git"],
    resumeParsed: true, profileCompletion: 58, createdAt: daysAgo(125), updatedAt: daysAgo(5),
  },
  {
    id: "prof-17", userId: DEMO_IDS.candidate17,
    headline: "DevOps / Platform Engineer | Kubernetes & Terraform | 3 Years",
    summary: "3-year DevOps engineer with a startup background.",
    location: "Pune, India",
    skills: ["Kubernetes", "Terraform", "AWS", "GitHub Actions", "Docker", "Helm", "Go basics", "Datadog"],
    experience: [{ id: "exp-23", title: "DevOps Engineer", company: "ClearTax", location: "Bangalore", startDate: "2023-09-01", endDate: "", current: true, description: "Maintaining AWS EKS + Terraform infra for tax-filing app." }],
    education: [{ id: "edu-17", degree: "B.E.", field: "ECE", institution: "BITS Goa", startDate: "2019-07-01", endDate: "2023-06-30", grade: "7.6 CGPA" }],
    projects: [{ id: "proj-17", name: "Terraform Modules Library", description: "Open-source collection of reusable Terraform modules.", technologies: ["Terraform", "AWS", "Go", "GitHub Actions"] }],
    certifications: [{ id: "cert-17", name: "AWS DevOps Engineer – Professional", issuer: "Amazon", issuedDate: "2025-05" }],
    technologies: ["Kubernetes", "Terraform", "AWS", "Docker", "Helm", "Datadog", "GitHub Actions"],
    resumeParsed: true, profileCompletion: 82, createdAt: daysAgo(120), updatedAt: daysAgo(6),
  },
  {
    id: "prof-18", userId: DEMO_IDS.candidate18,
    headline: "UX Designer | Figma & Research | 4 Years | Bangalore",
    summary: "4-year UX designer with a portfolio of 8 enterprise and consumer product redesigns.",
    phone: "+91-9833221100", location: "Bangalore, India",
    skills: ["Figma", "User Research", "Prototyping", "Usability Testing", "Design Systems", "Principle", "Zeplin"],
    experience: [
      { id: "exp-24", title: "Product Designer", company: "Swiggy", location: "Bangalore", startDate: "2022-04-01", endDate: "", current: true, description: "Redesigned restaurant onboarding flow, increasing completion rate by 35%." },
      { id: "exp-25", title: "UX Designer", company: "PixelCraft Agency", location: "Bangalore", startDate: "2021-01-01", endDate: "2022-03-31", current: false, description: "Delivered UX for 6 B2B SaaS clients." },
    ],
    education: [{ id: "edu-18", degree: "B.Des", field: "Visual Communication", institution: "NID Bangalore", startDate: "2016-07-01", endDate: "2020-06-30", grade: "8.2 CGPA" }],
    projects: [], certifications: [], technologies: ["Figma", "Principle", "Zeplin", "Hotjar", "Notion"],
    resumeParsed: true, profileCompletion: 85, createdAt: daysAgo(115), updatedAt: daysAgo(8),
  },
  {
    id: "prof-19", userId: DEMO_IDS.candidate19,
    headline: "Data Scientist | Python & ML | 6 Years | Mumbai",
    summary: "6-year data scientist specialising in credit risk modelling and churn prediction.",
    phone: "+91-9844332211", location: "Mumbai, India",
    skills: ["Python", "Scikit-learn", "XGBoost", "PyTorch", "SQL", "Tableau", "MLflow", "FastAPI", "R"],
    experience: [
      { id: "exp-26", title: "Senior Data Scientist", company: "Bajaj Finserv", location: "Mumbai", startDate: "2023-01-01", endDate: "", current: true, description: "Built credit scorecard for MSME loans with XGBoost." },
      { id: "exp-27", title: "Data Scientist", company: "Paytm", location: "Noida", startDate: "2020-06-01", endDate: "2022-12-31", current: false, description: "Built churn prediction model (recall 82%) for wallet users." },
    ],
    education: [{ id: "edu-19", degree: "M.Sc", field: "Statistics", institution: "IIT Bombay", startDate: "2018-07-01", endDate: "2020-06-30", grade: "8.6 CGPA" }],
    projects: [], certifications: [{ id: "cert-19", name: "Databricks Certified ML Professional", issuer: "Databricks", issuedDate: "2025-02" }],
    technologies: ["Python", "XGBoost", "PyTorch", "MLflow", "FastAPI", "SQL", "Tableau"],
    resumeParsed: true, profileCompletion: 93, createdAt: daysAgo(110), updatedAt: daysAgo(5),
  },
  {
    id: "prof-20", userId: DEMO_IDS.candidate20,
    headline: "HR Executive | Payroll & Compliance | 1 Year | Hyderabad",
    summary: "1-year HR professional with experience in payroll processing and employee lifecycle management.",
    location: "Hyderabad, India",
    skills: ["HR Operations", "Payroll (Darwinbox)", "EPF/ESIC Compliance", "Onboarding", "MS Excel", "Employee Relations"],
    experience: [{ id: "exp-28", title: "HR Executive", company: "WNS Global Services", location: "Hyderabad", startDate: "2025-08-01", endDate: "", current: true, description: "Processing monthly payroll for 300 employees on Darwinbox." }],
    education: [{ id: "edu-20", degree: "MBA", field: "Human Resources", institution: "Osmania University", startDate: "2023-07-01", endDate: "2025-06-30", grade: "7.9 CGPA" }],
    projects: [], certifications: [], technologies: ["Darwinbox", "MS Excel", "Greythr"],
    resumeParsed: true, profileCompletion: 70, createdAt: daysAgo(105), updatedAt: daysAgo(4),
  }
];
