import type { Application, CandidateMatch, Interview, Notification, InterviewFeedback } from "../types";
import { DEMO_IDS, daysAgo, daysFromNow, dateOnly } from "./seedHelpers";

type AppDef = { id: string; jobId: string; candidateId: string; companyId: string; status: Application["status"]; appliedDaysAgo: number; source: string; matchScore?: number; coverLetter?: string; recruiterNotes?: string; rejectionReason?: string; };

const appDefs: AppDef[] = [
  { id: "APP-A1C1JB1", jobId: DEMO_IDS.jobA1, candidateId: DEMO_IDS.candidate1, companyId: DEMO_IDS.companyA, status: "INTERVIEW", appliedDaysAgo: 33, source: "LinkedIn", matchScore: 91 },
  { id: "APP-A2C3JB1", jobId: DEMO_IDS.jobA1, candidateId: DEMO_IDS.candidate3, companyId: DEMO_IDS.companyA, status: "REVIEW", appliedDaysAgo: 29, source: "Career Site", matchScore: 72 },
  { id: "APP-A3C5JB1", jobId: DEMO_IDS.jobA1, candidateId: DEMO_IDS.candidate5, companyId: DEMO_IDS.companyA, status: "OFFER", appliedDaysAgo: 45, source: "Referral", matchScore: 96 },
  { id: "APP-A4C7JB1", jobId: DEMO_IDS.jobA1, candidateId: DEMO_IDS.candidate7, companyId: DEMO_IDS.companyA, status: "SCREENING", appliedDaysAgo: 10, source: "Naukri", matchScore: 58 },
  { id: "APP-A5C13JB1", jobId: DEMO_IDS.jobA1, candidateId: DEMO_IDS.candidate13, companyId: DEMO_IDS.companyA, status: "REJECTED", appliedDaysAgo: 40, source: "LinkedIn", matchScore: 62 },
  { id: "APP-A3C2JB2", jobId: DEMO_IDS.jobA2, candidateId: DEMO_IDS.candidate2, companyId: DEMO_IDS.companyA, status: "SHORTLISTED", appliedDaysAgo: 26, source: "Career Site", matchScore: 87 },
  { id: "APP-A4C8JB2", jobId: DEMO_IDS.jobA2, candidateId: DEMO_IDS.candidate8, companyId: DEMO_IDS.companyA, status: "INTERVIEW", appliedDaysAgo: 30, source: "LinkedIn", matchScore: 94 },
  { id: "APP-A5C16JB2", jobId: DEMO_IDS.jobA2, candidateId: DEMO_IDS.candidate16, companyId: DEMO_IDS.companyA, status: "APPLIED", appliedDaysAgo: 5, source: "Campus", matchScore: 55 },
  { id: "APP-A6C10JB2", jobId: DEMO_IDS.jobA2, candidateId: DEMO_IDS.candidate10, companyId: DEMO_IDS.companyA, status: "REJECTED", appliedDaysAgo: 25, source: "Agency", matchScore: 48 },
  { id: "APP-B1C9JB3", jobId: DEMO_IDS.jobA3, candidateId: DEMO_IDS.candidate9, companyId: DEMO_IDS.companyA, status: "FINAL_REVIEW", appliedDaysAgo: 38, source: "LinkedIn", matchScore: 89 },
  { id: "APP-B2C17JB3", jobId: DEMO_IDS.jobA3, candidateId: DEMO_IDS.candidate17, companyId: DEMO_IDS.companyA, status: "INTERVIEW", appliedDaysAgo: 35, source: "Referral", matchScore: 83 },
  { id: "APP-B3C5JB3", jobId: DEMO_IDS.jobA3, candidateId: DEMO_IDS.candidate5, companyId: DEMO_IDS.companyA, status: "REVIEW", appliedDaysAgo: 20, source: "Naukri", matchScore: 67 },
  { id: "APP-C1C4JB4", jobId: DEMO_IDS.jobA4, candidateId: DEMO_IDS.candidate4, companyId: DEMO_IDS.companyA, status: "HIRED", appliedDaysAgo: 58, source: "LinkedIn", matchScore: 97 },
  { id: "APP-C2C11JB4", jobId: DEMO_IDS.jobA4, candidateId: DEMO_IDS.candidate11, companyId: DEMO_IDS.companyA, status: "INTERVIEW", appliedDaysAgo: 42, source: "Career Site", matchScore: 92 },
  { id: "APP-C3C7JB4", jobId: DEMO_IDS.jobA4, candidateId: DEMO_IDS.candidate7, companyId: DEMO_IDS.companyA, status: "SCREENING", appliedDaysAgo: 12, source: "Naukri", matchScore: 54 },
  { id: "APP-D1C7JB5", jobId: DEMO_IDS.jobA5, candidateId: DEMO_IDS.candidate7, companyId: DEMO_IDS.companyA, status: "SHORTLISTED", appliedDaysAgo: 22, source: "Career Site", matchScore: 78 },
  { id: "APP-D2C19JB5", jobId: DEMO_IDS.jobA5, candidateId: DEMO_IDS.candidate19, companyId: DEMO_IDS.companyA, status: "REVIEW", appliedDaysAgo: 18, source: "LinkedIn", matchScore: 85 },
  { id: "APP-E1C6JB6", jobId: DEMO_IDS.jobA6, candidateId: DEMO_IDS.candidate6, companyId: DEMO_IDS.companyA, status: "INTERVIEW", appliedDaysAgo: 28, source: "Naukri", matchScore: 88 },
  { id: "APP-E2C3JB6", jobId: DEMO_IDS.jobA6, candidateId: DEMO_IDS.candidate3, companyId: DEMO_IDS.companyA, status: "APPLIED", appliedDaysAgo: 8, source: "Career Site", matchScore: 43 },
  { id: "APP-E3C10JB6", jobId: DEMO_IDS.jobA6, candidateId: DEMO_IDS.candidate10, companyId: DEMO_IDS.companyA, status: "SCREENING", appliedDaysAgo: 6, source: "Campus", matchScore: 61 },
  { id: "APP-F1C12JB7", jobId: DEMO_IDS.jobA7, candidateId: DEMO_IDS.candidate12, companyId: DEMO_IDS.companyA, status: "SHORTLISTED", appliedDaysAgo: 20, source: "LinkedIn", matchScore: 82 },
  { id: "APP-F2C19JB7", jobId: DEMO_IDS.jobA7, candidateId: DEMO_IDS.candidate19, companyId: DEMO_IDS.companyA, status: "REVIEW", appliedDaysAgo: 15, source: "Referral", matchScore: 75 },
  { id: "APP-G1C10JB8", jobId: DEMO_IDS.jobA8, candidateId: DEMO_IDS.candidate10, companyId: DEMO_IDS.companyA, status: "SHORTLISTED", appliedDaysAgo: 14, source: "Campus", matchScore: 74 },
  { id: "APP-G2C16JB8", jobId: DEMO_IDS.jobA8, candidateId: DEMO_IDS.candidate16, companyId: DEMO_IDS.companyA, status: "INTERVIEW", appliedDaysAgo: 12, source: "Campus", matchScore: 68 },
  { id: "APP-G3C3JB8", jobId: DEMO_IDS.jobA8, candidateId: DEMO_IDS.candidate3, companyId: DEMO_IDS.companyA, status: "APPLIED", appliedDaysAgo: 4, source: "Career Site", matchScore: 55 },
  { id: "APP-H1C5JB10", jobId: DEMO_IDS.jobA10, candidateId: DEMO_IDS.candidate5, companyId: DEMO_IDS.companyA, status: "FINAL_REVIEW", appliedDaysAgo: 52, source: "Referral", matchScore: 95 },
  { id: "APP-H2C13JB10", jobId: DEMO_IDS.jobA10, candidateId: DEMO_IDS.candidate13, companyId: DEMO_IDS.companyA, status: "WITHDRAWN", appliedDaysAgo: 44, source: "LinkedIn", matchScore: 80 },
  { id: "APP-I1C4JBB1", jobId: DEMO_IDS.jobB1, candidateId: DEMO_IDS.candidate4, companyId: DEMO_IDS.companyB, status: "INTERVIEW", appliedDaysAgo: 30, source: "LinkedIn", matchScore: 93 },
  { id: "APP-I2C11JBB1", jobId: DEMO_IDS.jobB1, candidateId: DEMO_IDS.candidate11, companyId: DEMO_IDS.companyB, status: "SHORTLISTED", appliedDaysAgo: 25, source: "Naukri", matchScore: 88 },
  { id: "APP-I3C14JBB1", jobId: DEMO_IDS.jobB1, candidateId: DEMO_IDS.candidate14, companyId: DEMO_IDS.companyB, status: "SCREENING", appliedDaysAgo: 10, source: "Career Site", matchScore: 64 },
  { id: "APP-J1C12JBB2", jobId: DEMO_IDS.jobB2, candidateId: DEMO_IDS.candidate12, companyId: DEMO_IDS.companyB, status: "INTERVIEW", appliedDaysAgo: 28, source: "LinkedIn", matchScore: 84 },
  { id: "APP-J2C15JBB2", jobId: DEMO_IDS.jobB2, candidateId: DEMO_IDS.candidate15, companyId: DEMO_IDS.companyB, status: "REVIEW", appliedDaysAgo: 20, source: "Naukri", matchScore: 66 },
  { id: "APP-J3C20JBB2", jobId: DEMO_IDS.jobB2, candidateId: DEMO_IDS.candidate20, companyId: DEMO_IDS.companyB, status: "APPLIED", appliedDaysAgo: 5, source: "Career Site", matchScore: 41 },
  { id: "APP-K1C14JBB3", jobId: DEMO_IDS.jobB3, candidateId: DEMO_IDS.candidate14, companyId: DEMO_IDS.companyB, status: "SHORTLISTED", appliedDaysAgo: 22, source: "LinkedIn", matchScore: 81 },
  { id: "APP-K2C4JBB3", jobId: DEMO_IDS.jobB3, candidateId: DEMO_IDS.candidate4, companyId: DEMO_IDS.companyB, status: "REJECTED", appliedDaysAgo: 30, source: "Agency", matchScore: 59 },
  { id: "APP-L1C15JBB4", jobId: DEMO_IDS.jobB4, candidateId: DEMO_IDS.candidate15, companyId: DEMO_IDS.companyB, status: "INTERVIEW", appliedDaysAgo: 24, source: "LinkedIn", matchScore: 77 },
  { id: "APP-L2C12JBB4", jobId: DEMO_IDS.jobB4, candidateId: DEMO_IDS.candidate12, companyId: DEMO_IDS.companyB, status: "SCREENING", appliedDaysAgo: 12, source: "Career Site", matchScore: 63 },
  { id: "APP-M1C20JBB6", jobId: DEMO_IDS.jobB6, candidateId: DEMO_IDS.candidate20, companyId: DEMO_IDS.companyB, status: "INTERVIEW", appliedDaysAgo: 14, source: "Naukri", matchScore: 82 },
  { id: "APP-M2C2JBB6", jobId: DEMO_IDS.jobB6, candidateId: DEMO_IDS.candidate2, companyId: DEMO_IDS.companyB, status: "REJECTED", appliedDaysAgo: 18, source: "Career Site", matchScore: 38 },
  { id: "APP-N1C13JGC1", jobId: DEMO_IDS.jobC1, candidateId: DEMO_IDS.candidate13, companyId: DEMO_IDS.companyC, status: "FINAL_REVIEW", appliedDaysAgo: 25, source: "LinkedIn", matchScore: 92 },
  { id: "APP-N2C17JGC1", jobId: DEMO_IDS.jobC1, candidateId: DEMO_IDS.candidate17, companyId: DEMO_IDS.companyC, status: "INTERVIEW", appliedDaysAgo: 20, source: "Referral", matchScore: 76 },
  { id: "APP-O1C10JGC2", jobId: DEMO_IDS.jobC2, candidateId: DEMO_IDS.candidate10, companyId: DEMO_IDS.companyC, status: "APPLIED", appliedDaysAgo: 5, source: "Campus", matchScore: 61 },
  { id: "APP-O2C16JGC2", jobId: DEMO_IDS.jobC2, candidateId: DEMO_IDS.candidate16, companyId: DEMO_IDS.companyC, status: "SCREENING", appliedDaysAgo: 8, source: "Campus", matchScore: 55 },
  { id: "APP-P1C9JGC3", jobId: DEMO_IDS.jobC3, candidateId: DEMO_IDS.candidate9, companyId: DEMO_IDS.companyC, status: "INTERVIEW", appliedDaysAgo: 12, source: "LinkedIn", matchScore: 85 },
  { id: "APP-P2C17JGC3", jobId: DEMO_IDS.jobC3, candidateId: DEMO_IDS.candidate17, companyId: DEMO_IDS.companyC, status: "SHORTLISTED", appliedDaysAgo: 10, source: "Referral", matchScore: 79 },
];

const STATUS_ORDER: Application["status"][] = ["APPLIED","SCREENING","REVIEW","SHORTLISTED","INTERVIEW","FINAL_REVIEW","OFFER","HIRED"];
function buildStatusHistory(appDef: AppDef): Application["statusHistory"] {
  const finalStatus = appDef.status;
  const path = finalStatus === "REJECTED" || finalStatus === "WITHDRAWN" ? [...STATUS_ORDER.slice(0, 3), finalStatus] : STATUS_ORDER.slice(0, Math.max(1, STATUS_ORDER.indexOf(finalStatus) + 1));
  let tsOffset = appDef.appliedDaysAgo;
  return path.map((s, i) => { if (i > 0) tsOffset -= Math.floor(Math.random() * 3) + 1; return { status: s as Application["status"], timestamp: daysAgo(Math.max(tsOffset, 0)) }; });
}

export const applications: Application[] = appDefs.map(d => ({
  id: d.id, jobId: d.jobId, candidateId: d.candidateId, companyId: d.companyId, status: d.status, appliedAt: daysAgo(d.appliedDaysAgo), updatedAt: daysAgo(Math.floor(d.appliedDaysAgo * 0.3)), statusHistory: buildStatusHistory(d), recruiterNotes: d.recruiterNotes,
}));

function buildMatch(id: string, jobId: string, candidateId: string, applicationId: string, score: number, strongMatchNames: string[], partialMatchNames: string[], missingNames: string[], explanation: string): CandidateMatch {
  const strong = strongMatchNames.map((n, i) => ({ requirementId: `r-${applicationId}-s${i}`, requirementName: n, requirementPriority: "MANDATORY" as const, status: "STRONG" as const, confidence: 0.85 + Math.random() * 0.12, evidenceText: `"${n} mentioned in work experience"`, evidenceSource: "experience" as const }));
  const partial = partialMatchNames.map((n, i) => ({ requirementId: `r-${applicationId}-p${i}`, requirementName: n, requirementPriority: "PREFERRED" as const, status: "PARTIAL" as const, confidence: 0.45 + Math.random() * 0.25, evidenceText: `"${n} found in skills section"`, evidenceSource: "experience" as const, relatedEvidence: "Some evidence found but depth unclear", recruiterAction: `Verify depth of ${n} experience` }));
  const missing = missingNames.map((n, i) => ({ requirementId: `r-${applicationId}-m${i}`, requirementName: n, requirementPriority: "MANDATORY" as const, status: "MISSING" as const, confidence: 0, missingEvidenceExplanation: `No evidence of ${n} found in resume.`, recruiterAction: `Ask directly about ${n} experience.` }));
  return {
    id, jobId, candidateId, applicationId, eligibility: score >= 70 ? "ELIGIBLE" : "CONDITIONAL", eligibilityReason: score >= 70 ? "Primary requirements have sufficient evidence." : "Some mandatory requirements lack evidence.", requiredSkillAlignment: score >= 85 ? "STRONG" : score >= 70 ? "MODERATE" : "WEAK", experienceRelevance: score >= 80 ? "STRONG" : "MODERATE", projectRelevance: score >= 75 ? "STRONG" : "MODERATE", evidenceConfidence: score >= 85 ? "HIGH" : "MEDIUM", domainRelevance: score >= 80 ? "STRONG" : "MODERATE", requirementAssessments: [...strong, ...partial, ...missing], strongMatches: strong, partialMatches: partial, missingRequirements: missing, uncertainRequirements: [], skillGaps: missing.map(m => ({ skillName: m.requirementName, jobPriority: "MANDATORY" as const, whyItMatters: `${m.requirementName} is required for this role.`, whatEvidenceIsMissing: `No ${m.requirementName} found in resume.`, suggestedInterviewQuestion: `Tell me about your experience with ${m.requirementName}.` })), overallScore: score, scoreComponents: [ { dimension: "Mandatory Skills", score: Math.min(100, score + 4), weight: 0.45, explanation: `${strong.length} skills matched directly` }, { dimension: "Experience Relevance", score: Math.min(100, score - 5), weight: 0.20, explanation: "Relevant work experience detected" }, { dimension: "Project Evidence", score: Math.min(100, score - 8), weight: 0.15, explanation: "Portfolio or project evidence assessed" }, { dimension: "Preferred Skills", score: Math.min(100, score - 10), weight: 0.20, explanation: `${partial.length} preferred skills partially matched` } ], explanation, evidenceSummary: `${strong.length} matched, ${partial.length} partial, ${missing.length} missing.`, recruiterRecommendations: strong.length >= 2 ? ["Strong profile — proceed to screen."] : ["Request additional evidence before proceeding."], modelProvider: "HireFlow AI", modelVersion: "7.0", knowledgeVersion: "2026-Q4", rulesVersion: "1.2", analyzedAt: daysAgo(Math.floor(Math.random() * 5) + 1), createdAt: daysAgo(Math.floor(Math.random() * 5) + 1),
  };
}

export const candidateMatches: CandidateMatch[] = [
  buildMatch("match-1", DEMO_IDS.jobA1, DEMO_IDS.candidate1, "APP-A1C1JB1", 91, ["Java", "Spring Boot", "PostgreSQL", "REST APIs"], ["Docker", "AWS"], [], "Strong Java + Spring Boot candidate with 3 years experience. AWS exposure through certification."),
  buildMatch("match-2", DEMO_IDS.jobA1, DEMO_IDS.candidate3, "APP-A2C3JB1", 72, ["Java", "Spring Boot"], ["SQL"], ["REST API Development"], "Java and Spring Boot fundamentals present. REST API experience not evidenced — must verify."),
  buildMatch("match-3", DEMO_IDS.jobA2, DEMO_IDS.candidate2, "APP-A3C2JB2", 87, ["React", "TypeScript", "CSS/Tailwind"], ["State Management", "Testing"], [], "Excellent React/TS frontend candidate. All mandatory requirements met."),
  buildMatch("match-4", DEMO_IDS.jobA1, DEMO_IDS.candidate5, "APP-A3C5JB1", 96, ["Java", "Spring Boot", "SQL", "REST APIs", "Microservices"], ["Docker", "AWS"], [], "8-year senior backend engineer. Exceeds all requirements. Production payment systems at scale. Strong Hire."),
  buildMatch("match-5", DEMO_IDS.jobA1, DEMO_IDS.candidate7, "APP-A4C7JB1", 58, ["Java"], [], ["Spring Boot", "REST APIs", "PostgreSQL"], "Only Java evidenced. Spring Boot and REST API experience missing."),
  buildMatch("match-6", DEMO_IDS.jobA2, DEMO_IDS.candidate8, "APP-A4C8JB2", 94, ["React", "TypeScript", "Testing"], ["CSS", "State Management"], [], "Senior React engineer with 4 years. D3.js, Next.js, Cypress evidence. Exceeds all requirements."),
  buildMatch("match-7", DEMO_IDS.jobA3, DEMO_IDS.candidate9, "APP-B1C9JB3", 89, ["Kubernetes", "Terraform", "AWS", "CI/CD"], ["Helm", "Monitoring"], [], "CKA-certified DevOps engineer. All mandatory infra requirements met."),
  buildMatch("match-8", DEMO_IDS.jobA3, DEMO_IDS.candidate17,"APP-B2C17JB3",83, ["Kubernetes", "Terraform", "AWS"], ["CI/CD", "Helm"], [], "Solid DevOps background with AWS DevOps Pro cert. Missing Monitoring evidence."),
  buildMatch("match-9", DEMO_IDS.jobA4, DEMO_IDS.candidate4, "APP-C1C4JB4", 97, ["Python", "Spark", "SQL", "Airflow"], [], [], "GCP-certified data engineer. 5 years with exact tech stack. Highest match on this job. Strong Hire."),
  buildMatch("match-10", DEMO_IDS.jobA4, DEMO_IDS.candidate11,"APP-C2C11JB4",92, ["Python", "Spark", "SQL", "Airflow", "dbt"], [], [], "Lead data engineer at PhonePe. All requirements exceeded. dbt certified."),
  buildMatch("match-11", DEMO_IDS.jobA5, DEMO_IDS.candidate7, "APP-D1C7JB5", 78, ["Python/PyTorch", "ML Training"], ["MLOps"], ["LLM Fine-tuning"], "Strong ML fundamentals and LLM project. MLOps experience limited."),
  buildMatch("match-12", DEMO_IDS.jobA5, DEMO_IDS.candidate19,"APP-D2C19JB5",85, ["Python", "ML Training", "MLOps"], ["LLM Fine-tuning"], [], "Senior data scientist with 6 years. MLflow and FastAPI deployment experience."),
  buildMatch("match-13", DEMO_IDS.jobA6, DEMO_IDS.candidate6, "APP-E1C6JB6", 88, ["Selenium/Playwright", "Java (testing)", "API Testing"], ["CI/CD"], [], "QA engineer with exactly matching Playwright/RestAssured stack."),
  buildMatch("match-14", DEMO_IDS.jobA7, DEMO_IDS.candidate12,"APP-F1C12JB7",82, ["SQL/Data Analysis", "Product Metrics"], ["Tableau", "A/B Testing"], [], "Career switcher from biz with 1 year product analytics. Tableau dashboard evidence."),
  buildMatch("match-15", DEMO_IDS.jobA8, DEMO_IDS.candidate10,"APP-G1C10JB8",74, ["React", "Java"], ["SQL"], [], "Fresher with relevant internship project. React + Spring Boot intern experience matches."),
  buildMatch("match-16", DEMO_IDS.jobA8, DEMO_IDS.candidate16,"APP-G2C16JB8",68, ["React"], [], ["Java/Node.js"], "Frontend-only fresher. No backend evidence. For intern role, acceptable with training."),
  buildMatch("match-17", DEMO_IDS.jobA10, DEMO_IDS.candidate5, "APP-H1C5JB10",95, ["Java/Kotlin", "Distributed Systems", "Kafka", "PostgreSQL"], ["System Design"], [], "Principal engineer with payment system experience at scale."),
  buildMatch("match-18", DEMO_IDS.jobB1, DEMO_IDS.candidate4, "APP-I1C4JBB1",93, ["Python", "Spark", "SQL", "Airflow"], [], [], "GCP-certified data engineer. All Beta Data Eng requirements met."),
  buildMatch("match-19", DEMO_IDS.jobB1, DEMO_IDS.candidate11,"APP-I2C11JBB1",88, ["Python", "Spark", "SQL"], ["Airflow"], [], "Lead data engineer with dbt + Airflow. Strong match for Beta."),
  buildMatch("match-20", DEMO_IDS.jobB2, DEMO_IDS.candidate12,"APP-J1C12JBB2",84, ["SQL", "Tableau"], ["Python"], [], "Product analyst with direct Tableau dashboard evidence. Good fit for data analyst."),
  buildMatch("match-21", DEMO_IDS.jobB3, DEMO_IDS.candidate14,"APP-K1C14JBB3",81, ["Python", "FastAPI", "PostgreSQL"], ["Docker"], [], "Exact FastAPI + PostgreSQL match. Clinical data API project directly relevant."),
  buildMatch("match-22", DEMO_IDS.jobB4, DEMO_IDS.candidate15,"APP-L1C15JBB4",77, ["Power BI", "DAX", "SQL"], [], [], "PL-300 certified BI analyst. Power BI and DAX requirements met. Good fit."),
  buildMatch("match-23", DEMO_IDS.jobB6, DEMO_IDS.candidate20,"APP-M1C20JBB6",82, ["HR Operations", "Payroll/Compliance"], ["HRMS"], [], "Darwinbox payroll experience directly matches requirement."),
  buildMatch("match-24", DEMO_IDS.jobC1, DEMO_IDS.candidate13,"APP-N1C13JGC1",92, ["Go", "REST APIs", "PostgreSQL"], ["Kubernetes"], [], "Razorpay Go engineer. gRPC and high-throughput API experience directly matches Gamma Backend role."),
  buildMatch("match-25", DEMO_IDS.jobC1, DEMO_IDS.candidate17,"APP-N2C17JGC1",76, ["Kubernetes"], ["Go basics"], ["gRPC"], "DevOps background with Go basics. Go API development experience not evidenced."),
  buildMatch("match-26", DEMO_IDS.jobC3, DEMO_IDS.candidate9, "APP-P1C9JGC3", 85, ["Kubernetes", "Terraform", "AWS"], [], [], "CKA-certified DevOps engineer. Matches Gamma DevOps role exactly."),
];

type IntDef = { id: string; applicationId: string; jobId: string; candidateId: string; interviewerId: string; companyId: string; stage: string; scheduledDaysFromNow: number; scheduledTime: string; duration: number; meetingLink?: string; feedback?: Omit<InterviewFeedback, "id" | "submittedAt">; notes?: string; };

const intDefs: IntDef[] = [
  { id: "int-1", applicationId: "APP-A1C1JB1", jobId: DEMO_IDS.jobA1, candidateId: DEMO_IDS.candidate1, interviewerId: DEMO_IDS.interviewerA1, companyId: DEMO_IDS.companyA, stage: "Technical Round", scheduledDaysFromNow: -14, scheduledTime: "10:00", duration: 60, meetingLink: "https://meet.google.com/abc-defg-hij", feedback: { interviewId: "int-1", interviewerId: DEMO_IDS.interviewerA1, technicalKnowledge: 5, problemSolving: 4, communication: 4, roleSpecific: 5, writtenFeedback: "Arjun demonstrated excellent Java and Spring Boot depth. Solved the distributed caching problem efficiently. Clear communicator. Strong Hire.", recommendation: "strong_hire", skillsObserved: ["Java", "Spring Boot", "REST APIs", "System Design"] } },
  { id: "int-2", applicationId: "APP-A1C1JB1", jobId: DEMO_IDS.jobA1, candidateId: DEMO_IDS.candidate1, interviewerId: DEMO_IDS.interviewerA2, companyId: DEMO_IDS.companyA, stage: "Managerial", scheduledDaysFromNow: 3, scheduledTime: "14:00", duration: 45, meetingLink: "https://meet.google.com/mng-arjun-alpha", notes: "Focus on team collaboration and ownership mindset." },
  { id: "int-3", applicationId: "APP-H1C5JB10", jobId: DEMO_IDS.jobA10, candidateId: DEMO_IDS.candidate5, interviewerId: DEMO_IDS.interviewerA3, companyId: DEMO_IDS.companyA, stage: "Technical Round 1", scheduledDaysFromNow: -20, scheduledTime: "11:00", duration: 90, meetingLink: "https://meet.google.com/tech1-suresh", feedback: { interviewId: "int-3", interviewerId: DEMO_IDS.interviewerA3, technicalKnowledge: 5, problemSolving: 5, communication: 5, roleSpecific: 5, writtenFeedback: "Exceptional. Deep distributed systems knowledge. Designed Kafka event sourcing system on whiteboard flawlessly. Best candidate interviewed this quarter.", recommendation: "strong_hire" } },
  { id: "int-4", applicationId: "APP-H1C5JB10", jobId: DEMO_IDS.jobA10, candidateId: DEMO_IDS.candidate5, interviewerId: DEMO_IDS.interviewerA1, companyId: DEMO_IDS.companyA, stage: "Managerial", scheduledDaysFromNow: -10, scheduledTime: "15:00", duration: 60, meetingLink: "https://meet.google.com/mgr-suresh", feedback: { interviewId: "int-4", interviewerId: DEMO_IDS.interviewerA1, technicalKnowledge: 4, problemSolving: 5, communication: 5, roleSpecific: 5, writtenFeedback: "Strong leadership mindset. Has led teams of 10+. Knows how to balance technical debt with velocity.", recommendation: "strong_hire" } },
  { id: "int-5", applicationId: "APP-B1C9JB3", jobId: DEMO_IDS.jobA3, candidateId: DEMO_IDS.candidate9, interviewerId: DEMO_IDS.interviewerA4, companyId: DEMO_IDS.companyA, stage: "Technical Round", scheduledDaysFromNow: -18, scheduledTime: "10:00", duration: 75, feedback: { interviewId: "int-5", interviewerId: DEMO_IDS.interviewerA4, technicalKnowledge: 5, problemSolving: 4, communication: 4, roleSpecific: 5, writtenFeedback: "Excellent Terraform and Kubernetes knowledge. EKS cluster design was thorough.", recommendation: "hire" } },
  { id: "int-6", applicationId: "APP-B1C9JB3", jobId: DEMO_IDS.jobA3, candidateId: DEMO_IDS.candidate9, interviewerId: DEMO_IDS.interviewerA5, companyId: DEMO_IDS.companyA, stage: "Culture Fit", scheduledDaysFromNow: 5, scheduledTime: "11:30", duration: 30, meetingLink: "https://meet.google.com/cult-ravi" },
  { id: "int-7", applicationId: "APP-A4C8JB2", jobId: DEMO_IDS.jobA2, candidateId: DEMO_IDS.candidate8, interviewerId: DEMO_IDS.interviewerA2, companyId: DEMO_IDS.companyA, stage: "Technical Round", scheduledDaysFromNow: 2, scheduledTime: "10:00", duration: 60, meetingLink: "https://meet.google.com/tech-divya" },
  { id: "int-8", applicationId: "APP-G2C16JB8", jobId: DEMO_IDS.jobA8, candidateId: DEMO_IDS.candidate16, interviewerId: DEMO_IDS.interviewerA6, companyId: DEMO_IDS.companyA, stage: "Technical Round", scheduledDaysFromNow: 7, scheduledTime: "15:00", duration: 45, meetingLink: "https://meet.google.com/intern-ananya" },
  { id: "int-9", applicationId: "APP-E1C6JB6", jobId: DEMO_IDS.jobA6, candidateId: DEMO_IDS.candidate6, interviewerId: DEMO_IDS.interviewerA3, companyId: DEMO_IDS.companyA, stage: "Technical Round", scheduledDaysFromNow: -8, scheduledTime: "11:00", duration: 60, feedback: { interviewId: "int-9", interviewerId: DEMO_IDS.interviewerA3, technicalKnowledge: 4, problemSolving: 4, communication: 5, roleSpecific: 4, writtenFeedback: "Good Playwright automation knowledge. API testing with RestAssured solid. CI/CD integration a bit basic but teachable.", recommendation: "hire" } },
  { id: "int-10", applicationId: "APP-B2C17JB3", jobId: DEMO_IDS.jobA3, candidateId: DEMO_IDS.candidate17, interviewerId: DEMO_IDS.interviewerA1, companyId: DEMO_IDS.companyA, stage: "Technical Round", scheduledDaysFromNow: -5, scheduledTime: "14:00", duration: 60 },
  { id: "int-11", applicationId: "APP-C2C11JB4", jobId: DEMO_IDS.jobA4, candidateId: DEMO_IDS.candidate11, interviewerId: DEMO_IDS.interviewerA5, companyId: DEMO_IDS.companyA, stage: "Technical Round", scheduledDaysFromNow: -3, scheduledTime: "10:00", duration: 75 },
  { id: "int-12", applicationId: "APP-I1C4JBB1", jobId: DEMO_IDS.jobB1, candidateId: DEMO_IDS.candidate4, interviewerId: DEMO_IDS.interviewerB1, companyId: DEMO_IDS.companyB, stage: "Technical Round", scheduledDaysFromNow: -7, scheduledTime: "11:00", duration: 75, feedback: { interviewId: "int-12", interviewerId: DEMO_IDS.interviewerB1, technicalKnowledge: 5, problemSolving: 4, communication: 4, roleSpecific: 5, writtenFeedback: "GCP-certified. Spark pipeline design excellent. Airflow DAG design clean. Strong Hire.", recommendation: "strong_hire" } },
  { id: "int-13", applicationId: "APP-J1C12JBB2", jobId: DEMO_IDS.jobB2, candidateId: DEMO_IDS.candidate12, interviewerId: DEMO_IDS.interviewerB1, companyId: DEMO_IDS.companyB, stage: "Technical Round", scheduledDaysFromNow: 6, scheduledTime: "14:00", duration: 45, meetingLink: "https://meet.google.com/beta-meghana" },
  { id: "int-14", applicationId: "APP-M1C20JBB6", jobId: DEMO_IDS.jobB6, candidateId: DEMO_IDS.candidate20, interviewerId: DEMO_IDS.interviewerB1, companyId: DEMO_IDS.companyB, stage: "HR Screen", scheduledDaysFromNow: -2, scheduledTime: "12:00", duration: 30 },
  { id: "int-15", applicationId: "APP-N1C13JGC1", jobId: DEMO_IDS.jobC1, candidateId: DEMO_IDS.candidate13, interviewerId: DEMO_IDS.interviewerC1, companyId: DEMO_IDS.companyC, stage: "Technical Round", scheduledDaysFromNow: -6, scheduledTime: "10:00", duration: 90, feedback: { interviewId: "int-15", interviewerId: DEMO_IDS.interviewerC1, technicalKnowledge: 5, problemSolving: 5, communication: 4, roleSpecific: 5, writtenFeedback: "Exceptional Go skills. gRPC design was production-quality. PostgreSQL schema design thoughtful. Strong Hire.", recommendation: "strong_hire" } },
  { id: "int-16", applicationId: "APP-P1C9JGC3", jobId: DEMO_IDS.jobC3, candidateId: DEMO_IDS.candidate9, interviewerId: DEMO_IDS.interviewerC1, companyId: DEMO_IDS.companyC, stage: "Technical Round", scheduledDaysFromNow: 4, scheduledTime: "11:00", duration: 60, meetingLink: "https://meet.google.com/gamma-ravi" },
  { id: "int-17", applicationId: "APP-A1C1JB1", jobId: DEMO_IDS.jobA1, candidateId: DEMO_IDS.candidate1, interviewerId: DEMO_IDS.interviewerA6, companyId: DEMO_IDS.companyA, stage: "HR Screen", scheduledDaysFromNow: -22, scheduledTime: "09:00", duration: 30, feedback: { interviewId: "int-17", interviewerId: DEMO_IDS.interviewerA6, technicalKnowledge: 3, problemSolving: 3, communication: 5, roleSpecific: 4, writtenFeedback: "Excellent communication. Notice period 30 days — manageable. Expected CTC ₹14L — within budget. Good culture fit. Proceed.", recommendation: "hire" } },
];

function computeInterviewStatus(daysFromNow: number, hasFeedback: boolean): Interview["status"] {
  if (daysFromNow >= 0) return "scheduled";
  if (hasFeedback) return "completed";
  return "completed";
}

export const interviews: Interview[] = intDefs.map(d => {
  const scheduledDate = d.scheduledDaysFromNow >= 0 ? dateOnly(daysFromNow(d.scheduledDaysFromNow)) : dateOnly(daysAgo(-d.scheduledDaysFromNow));
  const status = computeInterviewStatus(d.scheduledDaysFromNow, Boolean(d.feedback));
  const interview: Interview = { id: d.id, applicationId: d.applicationId, jobId: d.jobId, candidateId: d.candidateId, interviewerId: d.interviewerId, companyId: d.companyId, stage: d.stage, scheduledDate, scheduledTime: d.scheduledTime, duration: d.duration, meetingLink: d.meetingLink, notes: d.notes, status, createdAt: daysAgo(-d.scheduledDaysFromNow + 5), updatedAt: daysAgo(Math.abs(d.scheduledDaysFromNow) > 2 ? 1 : 0) };
  if (d.feedback) { (interview as any).feedback = { ...d.feedback, id: `fb-${d.id}`, submittedAt: daysAgo(Math.abs(d.scheduledDaysFromNow) > 1 ? 1 : 0) }; }
  return interview;
});

export const notifications: Notification[] = [
  { id: "notif-1", userId: DEMO_IDS.bhrA, type: "new_application", title: "New Application", message: "Arjun Mehta applied for Backend Developer", read: true, link: "/company/jobs/job-backend-dev", createdAt: daysAgo(33) },
  { id: "notif-2", userId: DEMO_IDS.bhrA, type: "new_application", title: "New Application", message: "Rohit Verma applied for Backend Developer", read: true, link: "/company/jobs/job-backend-dev", createdAt: daysAgo(29) },
  { id: "notif-3", userId: DEMO_IDS.bhrA, type: "new_application", title: "New Application", message: "Suresh Babu applied for Backend Developer", read: false, link: "/company/jobs/job-backend-dev", createdAt: daysAgo(45) },
  { id: "notif-4", userId: DEMO_IDS.bhrA, type: "new_application", title: "New Application", message: "Pooja Krishnan applied for Data Engineer", read: false, link: "/company/jobs/job-data-eng-alpha", createdAt: daysAgo(42) },
  { id: "notif-5", userId: DEMO_IDS.bhrA, type: "interview_feedback", title: "Feedback Submitted", message: "Vikram Singh submitted feedback for Arjun Mehta", read: false, link: "/company/candidates/user-cand-1", createdAt: daysAgo(13) },
  { id: "notif-6", userId: DEMO_IDS.bhrA, type: "feedback_overdue", title: "Feedback Overdue", message: "Vikram Singh: feedback for Rahul Bose is 5 days overdue", read: false, link: "/company/candidates/user-cand-17", createdAt: daysAgo(1) },
  { id: "notif-7", userId: DEMO_IDS.bhrA, type: "offer_accepted", title: "Offer Accepted!", message: "Pooja Krishnan accepted the Data Engineer offer", read: false, link: "/company/offers", createdAt: daysAgo(2) },
  { id: "notif-8", userId: DEMO_IDS.hrA, type: "new_application", title: "New Application", message: "Divya Pillai applied for Frontend Developer", read: false, link: "/company/jobs/job-frontend-dev", createdAt: daysAgo(30) },
  { id: "notif-9", userId: DEMO_IDS.hrA, type: "interview_scheduled", title: "Interview Scheduled", message: "Interview scheduled with Divya Pillai for Frontend Developer", read: false, link: "/company/jobs/job-frontend-dev", createdAt: daysAgo(12) },
  { id: "notif-10", userId: DEMO_IDS.interviewerA1, type: "interview_scheduled", title: "Interview Assigned", message: "Technical Round with Arjun Mehta on 20 Sep 2026", read: true, link: "/interviewer/interviews/int-1", createdAt: daysAgo(19) },
  { id: "notif-11", userId: DEMO_IDS.interviewerA1, type: "interview_scheduled", title: "Interview Assigned", message: "Managerial with Suresh Babu — please submit feedback", read: false, link: "/interviewer/interviews/int-4", createdAt: daysAgo(10) },
  { id: "notif-12", userId: DEMO_IDS.interviewerA1, type: "feedback_overdue", title: "Feedback Overdue", message: "Technical Round with Rahul Bose — feedback is 5 days overdue", read: false, link: "/interviewer/interviews/int-10", createdAt: daysAgo(1) },
  { id: "notif-13", userId: DEMO_IDS.candidate1, type: "interview_scheduled", title: "Interview Invitation", message: "HR Screen with Alpha Technologies on 12 Sep 2026", read: true, link: "/candidate/interviews", createdAt: daysAgo(22) },
  { id: "notif-14", userId: DEMO_IDS.candidate1, type: "interview_scheduled", title: "Interview Invitation", message: "Technical Round with Alpha Technologies on 20 Sep 2026", read: true, link: "/candidate/interviews", createdAt: daysAgo(14) },
  { id: "notif-15", userId: DEMO_IDS.candidate1, type: "upcoming_interview", title: "Upcoming Interview", message: "Managerial interview in 3 days — Alpha Technologies", read: false, link: "/candidate/interviews", createdAt: daysAgo(1) },
  { id: "notif-16", userId: DEMO_IDS.candidate1, type: "status_changed", title: "Application Update", message: "Your Backend Developer application moved to Interview stage", read: true, link: "/candidate/applications/APP-A1C1JB1", createdAt: daysAgo(23) },
  { id: "notif-17", userId: DEMO_IDS.bhrB, type: "new_application", title: "New Application", message: "Pooja Krishnan applied for Data Engineer", read: false, link: "/company/jobs/job-data-eng", createdAt: daysAgo(30) },
  { id: "notif-18", userId: DEMO_IDS.bhrB, type: "interview_feedback", title: "Feedback Submitted", message: "Suresh Pillai submitted feedback for Pooja Krishnan", read: false, link: "/company/candidates/user-cand-4", createdAt: daysAgo(6) },
  { id: "notif-19", userId: DEMO_IDS.bhrC, type: "interview_feedback", title: "Feedback Submitted", message: "Nikhil Joshi submitted feedback for Ajay Kulkarni", read: false, link: "/company/candidates/user-cand-13", createdAt: daysAgo(5) },
  { id: "notif-20", userId: DEMO_IDS.bhrC, type: "new_application", title: "New Application", message: "Ravi Chandran applied for DevOps Engineer", read: false, link: "/company/jobs/job-gamma-devops", createdAt: daysAgo(12) },
  { id: "notif-21", userId: DEMO_IDS.interviewerA2, type: "interview_scheduled", title: "Interview Assigned", message: "Managerial Round with Arjun Mehta in 3 days", read: false, link: "/interviewer/interviews/int-2", createdAt: daysAgo(2) },
  { id: "notif-22", userId: DEMO_IDS.interviewerA2, type: "interview_scheduled", title: "Interview Assigned", message: "Technical Round with Divya Pillai in 2 days", read: false, link: "/interviewer/interviews/int-7", createdAt: daysAgo(1) },
];
