import { TaxonomySkill } from './types';

export const BACKEND_FRAMEWORKS: TaxonomySkill[] = [
  {
    id: 'node_js',
    canonical: 'Node.js',
    category: 'backend',
    aliases: ['Node.js', 'NodeJS', 'Node'],
    implies: ['javascript'],
    substitutes: [{ id: 'bun', similarity: 0.8 }, { id: 'deno', similarity: 0.8 }],
    weight: 5,
  },
  {
    id: 'express',
    canonical: 'Express',
    category: 'backend',
    aliases: ['Express', 'Express.js', 'ExpressJS'],
    implies: ['node_js', 'javascript'],
    substitutes: [{ id: 'fastify', similarity: 0.85 }, { id: 'nestjs', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'nestjs',
    canonical: 'NestJS',
    category: 'backend',
    aliases: ['NestJS', 'Nest.js'],
    implies: ['typescript', 'nodejs'],
    substitutes: [{ id: 'expressjs', similarity: 0.75 }, { id: 'spring_boot', similarity: 0.65 }],
    weight: 5,
  },
  {
    id: 'fastify',
    canonical: 'Fastify',
    category: 'backend',
    aliases: ['Fastify'],
    implies: ['nodejs'],
    substitutes: [{ id: 'expressjs', similarity: 0.85 }],
    weight: 4,
  },
  {
    id: 'spring_boot',
    canonical: 'Spring Boot',
    category: 'backend',
    aliases: ['Spring Boot', 'SpringBoot', 'Spring Cloud', 'Spring Framework', 'Spring MVC'],
    implies: ['java'],
    substitutes: [{ id: 'quarkus', similarity: 0.75 }, { id: 'micronaut', similarity: 0.75 }, { id: 'aspnet_core', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'hibernate',
    canonical: 'Hibernate',
    category: 'backend',
    aliases: ['Hibernate', 'Hibernate ORM', 'JPA', 'Java Persistence API'],
    implies: ['java', 'sql'],
    weight: 4,
  },
  {
    id: 'quarkus',
    canonical: 'Quarkus',
    category: 'backend',
    aliases: ['Quarkus'],
    implies: ['java'],
    substitutes: [{ id: 'spring_boot', similarity: 0.75 }],
    weight: 4,
  },
  {
    id: 'django',
    canonical: 'Django',
    category: 'backend',
    aliases: ['Django', 'Django REST Framework', 'DRF'],
    implies: ['python'],
    substitutes: [{ id: 'fastapi', similarity: 0.75 }, { id: 'flask', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'fastapi',
    canonical: 'FastAPI',
    category: 'backend',
    aliases: ['FastAPI'],
    implies: ['python'],
    substitutes: [{ id: 'django', similarity: 0.75 }, { id: 'flask', similarity: 0.8 }],
    weight: 5,
  },
  {
    id: 'flask',
    canonical: 'Flask',
    category: 'backend',
    aliases: ['Flask'],
    implies: ['python'],
    substitutes: [{ id: 'fastapi', similarity: 0.8 }, { id: 'django', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'aspnet_core',
    canonical: 'ASP.NET Core',
    category: 'backend',
    aliases: ['ASP.NET Core', 'ASP.NET', '.NET Core', '.NET 6', '.NET 7', '.NET 8', 'Entity Framework', 'EF Core'],
    implies: ['csharp'],
    substitutes: [{ id: 'spring_boot', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'ruby_on_rails',
    canonical: 'Ruby on Rails',
    category: 'backend',
    aliases: ['Ruby on Rails', 'Rails', 'RoR'],
    implies: ['ruby'],
    substitutes: [{ id: 'django', similarity: 0.65 }],
    weight: 4,
  },
  {
    id: 'laravel',
    canonical: 'Laravel',
    category: 'backend',
    aliases: ['Laravel'],
    implies: ['php'],
    substitutes: [{ id: 'symfony', similarity: 0.8 }],
    weight: 4,
  },
  {
    id: 'symfony',
    canonical: 'Symfony',
    category: 'backend',
    aliases: ['Symfony'],
    implies: ['php'],
    weight: 3,
  },
  {
    id: 'gin',
    canonical: 'Gin',
    category: 'backend',
    aliases: ['Gin', 'Gin Gonic', 'Gin-Gonic'],
    implies: ['go'],
    substitutes: [{ id: 'echo', similarity: 0.85 }],
    weight: 4,
  },
  {
    id: 'echo',
    canonical: 'Echo',
    category: 'backend',
    aliases: ['Echo web framework'],
    implies: ['go'],
    weight: 3,
  },
  {
    id: 'fiber',
    canonical: 'Fiber',
    category: 'backend',
    aliases: ['Fiber framework'],
    implies: ['go'],
    weight: 3,
  },
  {
    id: 'actix_web',
    canonical: 'Actix Web / Axum',
    category: 'backend',
    aliases: ['Actix', 'Actix Web', 'Actix-web', 'Axum'],
    implies: ['rust'],
    weight: 4,
  },
  {
    id: 'phoenix',
    canonical: 'Phoenix',
    category: 'backend',
    aliases: ['Phoenix Framework', 'Phoenix LiveView'],
    implies: ['elixir'],
    weight: 3,
  },
  {
    id: 'ktor',
    canonical: 'Ktor',
    category: 'backend',
    aliases: ['Ktor'],
    implies: ['kotlin'],
    weight: 3,
  },
  {
    id: 'rest_apis',
    canonical: 'RESTful APIs',
    category: 'backend',
    aliases: ['REST', 'RESTful API', 'REST API', 'RESTful', 'REST APIs'],
    substitutes: [{ id: 'graphql', similarity: 0.6 }, { id: 'grpc', similarity: 0.6 }],
    weight: 5,
  },
  {
    id: 'graphql',
    canonical: 'GraphQL',
    category: 'backend',
    aliases: ['GraphQL', 'Apollo Server', 'Apollo GraphQL', 'Relay'],
    substitutes: [{ id: 'rest_apis', similarity: 0.6 }, { id: 'grpc', similarity: 0.5 }],
    weight: 5,
  },
  {
    id: 'grpc',
    canonical: 'gRPC',
    category: 'backend',
    aliases: ['gRPC', 'Protocol Buffers', 'Protobuf'],
    substitutes: [{ id: 'rest_apis', similarity: 0.6 }],
    weight: 4,
  },
  {
    id: 'microservices',
    canonical: 'Microservices Architecture',
    category: 'backend',
    aliases: ['Microservices', 'Microservice Architecture', 'Micro-services', 'Service-Oriented Architecture', 'SOA'],
    weight: 5,
  },
  {
    id: 'event_driven',
    canonical: 'Event-Driven Architecture',
    category: 'backend',
    aliases: ['Event-Driven Architecture', 'Event Driven', 'EDA', 'Pub/Sub Architecture', 'Event Sourcing', 'CQRS'],
    weight: 5,
  },
  {
    id: 'system_design',
    canonical: 'System Design',
    category: 'backend',
    aliases: ['System Design', 'High Level Design', 'HLD', 'Low Level Design', 'LLD', 'Architectural Design'],
    weight: 5,
  },
  {
    id: 'distributed_systems',
    canonical: 'Distributed Systems',
    category: 'backend',
    aliases: ['Distributed Systems', 'Distributed Computing', 'CAP Theorem', 'Consensus Algorithms', 'Raft', 'Paxos'],
    weight: 5,
  },
  {
    id: 'caching_strategies',
    canonical: 'Caching Strategies',
    category: 'backend',
    aliases: ['Caching', 'Cache Invalidation', 'Redis Caching', 'Memcached Caching', 'CDN Caching'],
    weight: 4,
  },
  {
    id: 'websockets_backend',
    canonical: 'WebSockets & Realtime',
    category: 'backend',
    aliases: ['WebSockets', 'Socket.io', 'Server-Sent Events', 'SSE', 'Real-time Communication'],
    weight: 4,
  },
  {
    id: 'jwt_auth',
    canonical: 'Authentication & Authorization',
    category: 'backend',
    aliases: ['JWT', 'JSON Web Tokens', 'OAuth 2.0', 'OAuth', 'OpenID Connect', 'OIDC', 'SAML', 'SSO'],
    weight: 4,
  },
  {
    id: 'message_queues',
    canonical: 'Message Queues',
    category: 'backend',
    aliases: ['Message Queue', 'Message Queues', 'RabbitMQ', 'ActiveMQ', 'BullMQ', 'Celery', 'Amazon SQS'],
    weight: 4,
  },
  {
    id: 'api_gateway',
    canonical: 'API Gateway',
    category: 'backend',
    aliases: ['API Gateway', 'Kong', 'KrakenD', 'Zuul', 'Ocelot', 'AWS API Gateway'],
    weight: 4,
  },
  {
    id: 'serverless_arch',
    canonical: 'Serverless Architecture',
    category: 'backend',
    aliases: ['Serverless', 'AWS Lambda', 'Cloud Functions', 'Azure Functions'],
    weight: 4,
  },
  {
    id: 'clean_architecture',
    canonical: 'Clean Architecture / DDD',
    category: 'backend',
    aliases: ['Clean Architecture', 'Hexagonal Architecture', 'Domain-Driven Design', 'DDD', 'SOLID Principles'],
    weight: 4,
  },
];
