import { TaxonomySkill } from './types';

export const CLOUD_DEVOPS_INFRA: TaxonomySkill[] = [
  {
    id: 'aws',
    canonical: 'AWS',
    category: 'cloud_devops',
    aliases: ['AWS', 'Amazon Web Services', 'Amazon Cloud'],
    substitutes: [{ id: 'gcp', similarity: 0.65 }, { id: 'azure', similarity: 0.65 }],
    weight: 5,
  },
  {
    id: 'gcp',
    canonical: 'GCP',
    category: 'cloud_devops',
    aliases: ['GCP', 'Google Cloud Platform', 'Google Cloud'],
    substitutes: [{ id: 'aws', similarity: 0.65 }, { id: 'azure', similarity: 0.65 }],
    weight: 5,
  },
  {
    id: 'azure',
    canonical: 'Azure',
    category: 'cloud_devops',
    aliases: ['Azure', 'Microsoft Azure'],
    substitutes: [{ id: 'aws', similarity: 0.65 }, { id: 'gcp', similarity: 0.65 }],
    weight: 5,
  },
  {
    id: 'docker',
    canonical: 'Docker',
    category: 'cloud_devops',
    aliases: ['Docker', 'Docker Compose', 'Containerization', 'Containers'],
    substitutes: [{ id: 'podman', similarity: 0.85 }],
    weight: 5,
  },
  {
    id: 'podman',
    canonical: 'Podman',
    category: 'cloud_devops',
    aliases: ['Podman'],
    substitutes: [{ id: 'docker', similarity: 0.85 }],
    weight: 3,
  },
  {
    id: 'kubernetes',
    canonical: 'Kubernetes',
    category: 'cloud_devops',
    aliases: ['Kubernetes', 'K8s', 'EKS', 'GKE', 'AKS', 'K9s'],
    implies: ['docker'],
    weight: 5,
  },
  {
    id: 'helm',
    canonical: 'Helm',
    category: 'cloud_devops',
    aliases: ['Helm', 'Helm Charts'],
    implies: ['kubernetes'],
    weight: 4,
  },
  {
    id: 'service_mesh',
    canonical: 'Service Mesh (Istio / Envoy)',
    category: 'cloud_devops',
    aliases: ['Istio', 'Linkerd', 'Envoy', 'Service Mesh'],
    implies: ['kubernetes'],
    weight: 4,
  },
  {
    id: 'terraform',
    canonical: 'Terraform',
    category: 'cloud_devops',
    aliases: ['Terraform', 'HCL', 'HashiCorp Terraform'],
    substitutes: [{ id: 'pulumi', similarity: 0.75 }, { id: 'cloudformation', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'pulumi',
    canonical: 'Pulumi',
    category: 'cloud_devops',
    aliases: ['Pulumi'],
    substitutes: [{ id: 'terraform', similarity: 0.75 }],
    weight: 3,
  },
  {
    id: 'cloudformation',
    canonical: 'AWS CloudFormation / CDK',
    category: 'cloud_devops',
    aliases: ['CloudFormation', 'AWS CDK', 'CDK'],
    implies: ['aws'],
    substitutes: [{ id: 'terraform', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'ansible',
    canonical: 'Ansible',
    category: 'cloud_devops',
    aliases: ['Ansible', 'Playbooks'],
    weight: 4,
  },
  {
    id: 'ci_cd',
    canonical: 'CI/CD Pipelines',
    category: 'cloud_devops',
    aliases: ['CI/CD', 'Continuous Integration', 'Continuous Delivery', 'Continuous Deployment'],
    weight: 5,
  },
  {
    id: 'github_actions',
    canonical: 'GitHub Actions',
    category: 'cloud_devops',
    aliases: ['GitHub Actions', 'GHA'],
    implies: ['ci_cd'],
    substitutes: [{ id: 'gitlab_ci', similarity: 0.8 }, { id: 'jenkins', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'gitlab_ci',
    canonical: 'GitLab CI/CD',
    category: 'cloud_devops',
    aliases: ['GitLab CI', 'GitLab Pipelines'],
    implies: ['ci_cd'],
    substitutes: [{ id: 'github_actions', similarity: 0.8 }, { id: 'jenkins', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'jenkins',
    canonical: 'Jenkins',
    category: 'cloud_devops',
    aliases: ['Jenkins', 'Jenkinsfile'],
    implies: ['ci_cd'],
    substitutes: [{ id: 'github_actions', similarity: 0.7 }, { id: 'gitlab_ci', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'argocd',
    canonical: 'ArgoCD / GitOps',
    category: 'cloud_devops',
    aliases: ['ArgoCD', 'Argo CD', 'GitOps', 'Flux CD'],
    implies: ['kubernetes', 'ci_cd'],
    weight: 4,
  },
  {
    id: 'prometheus',
    canonical: 'Prometheus',
    category: 'cloud_devops',
    aliases: ['Prometheus', 'PromQL'],
    weight: 4,
  },
  {
    id: 'grafana',
    canonical: 'Grafana',
    category: 'cloud_devops',
    aliases: ['Grafana'],
    weight: 4,
  },
  {
    id: 'datadog',
    canonical: 'Datadog / APM',
    category: 'cloud_devops',
    aliases: ['Datadog', 'New Relic', 'Dynatrace', 'APM'],
    weight: 4,
  },
  {
    id: 'opentelemetry',
    canonical: 'OpenTelemetry',
    category: 'cloud_devops',
    aliases: ['OpenTelemetry', 'OTel', 'Distributed Tracing', 'Jaeger'],
    weight: 4,
  },
  {
    id: 'nginx',
    canonical: 'Nginx',
    category: 'cloud_devops',
    aliases: ['Nginx', 'Reverse Proxy', 'Load Balancing', 'HAProxy', 'Traefik'],
    weight: 4,
  },
  {
    id: 'linux_sysadmin',
    canonical: 'Linux Administration',
    category: 'cloud_devops',
    aliases: ['Linux', 'Ubuntu', 'Debian', 'RHEL', 'CentOS', 'Linux Kernel', 'System Administration'],
    weight: 5,
  },
  {
    id: 'site_reliability_engineering',
    canonical: 'Site Reliability Engineering (SRE)',
    category: 'cloud_devops',
    aliases: ['SRE', 'Site Reliability Engineering', 'SLO', 'SLA', 'SLI', 'Error Budgets', 'Incident Response'],
    weight: 5,
  },
];
