import { TaxonomySkill } from './types';

export const CORE_ENGINEERING_TOOLS: TaxonomySkill[] = [
  {
    id: 'autocad',
    canonical: 'AutoCAD',
    category: 'core_engineering',
    aliases: ['AutoCAD', 'AutoDesk AutoCAD', '2D CAD'],
    weight: 4,
  },
  {
    id: 'solidworks',
    canonical: 'SolidWorks',
    category: 'core_engineering',
    aliases: ['SolidWorks', 'Solid Works', '3D Modeling CAD'],
    substitutes: [{ id: 'catia', similarity: 0.8 }, { id: 'creo', similarity: 0.8 }],
    weight: 5,
  },
  {
    id: 'catia',
    canonical: 'CATIA',
    category: 'core_engineering',
    aliases: ['CATIA', 'CATIA V5', 'Dassault CATIA'],
    substitutes: [{ id: 'solidworks', similarity: 0.8 }, { id: 'siemens_nx', similarity: 0.85 }],
    weight: 5,
  },
  {
    id: 'creo',
    canonical: 'PTC Creo',
    category: 'core_engineering',
    aliases: ['Creo', 'PTC Creo', 'Pro/ENGINEER', 'ProE'],
    substitutes: [{ id: 'solidworks', similarity: 0.8 }],
    weight: 4,
  },
  {
    id: 'siemens_nx',
    canonical: 'Siemens NX',
    category: 'core_engineering',
    aliases: ['Siemens NX', 'Unigraphics NX', 'UG NX'],
    substitutes: [{ id: 'catia', similarity: 0.85 }],
    weight: 5,
  },
  {
    id: 'ansys',
    canonical: 'ANSYS / FEA Simulation',
    category: 'core_engineering',
    aliases: ['ANSYS', 'ANSYS Mechanical', 'ANSYS Workbench', 'FEA', 'Finite Element Analysis'],
    substitutes: [{ id: 'abaqus', similarity: 0.8 }],
    weight: 5,
  },
  {
    id: 'cfd_fluent',
    canonical: 'Computational Fluid Dynamics (CFD)',
    category: 'core_engineering',
    aliases: ['CFD', 'ANSYS Fluent', 'Fluent', 'OpenFOAM', 'Computational Fluid Dynamics'],
    weight: 5,
  },
  {
    id: 'abaqus',
    canonical: 'Abaqus / HyperMesh',
    category: 'core_engineering',
    aliases: ['Abaqus', 'HyperMesh', 'Altair HyperMesh'],
    substitutes: [{ id: 'ansys', similarity: 0.8 }],
    weight: 4,
  },
  {
    id: 'plc_programming',
    canonical: 'PLC Programming',
    category: 'core_engineering',
    aliases: ['PLC', 'PLC Programming', 'Ladder Logic', 'Siemens S7', 'Allen Bradley', 'Rockwell Automation'],
    weight: 5,
  },
  {
    id: 'scada_hmi',
    canonical: 'SCADA & HMI Systems',
    category: 'core_engineering',
    aliases: ['SCADA', 'HMI', 'Supervisory Control and Data Acquisition', 'Wonderware', 'Ignition SCADA'],
    implies: ['plc_programming'],
    weight: 4,
  },
  {
    id: 'robotics_ros',
    canonical: 'Robotics & ROS',
    category: 'core_engineering',
    aliases: ['ROS', 'Robot Operating System', 'ROS2', 'Industrial Robotics', 'FANUC', 'KUKA'],
    weight: 5,
  },
  {
    id: 'gdt_standards',
    canonical: 'GD&T (Geometric Dimensioning)',
    category: 'core_engineering',
    aliases: ['GD&T', 'Geometric Dimensioning and Tolerancing', 'ASME Y14.5', 'Tolerance Stackup'],
    weight: 4,
  },
  {
    id: 'dfm_dfa',
    canonical: 'DFM / DFA Engineering',
    category: 'core_engineering',
    aliases: ['DFM', 'DFA', 'Design for Manufacturing', 'Design for Assembly'],
    weight: 4,
  },
  {
    id: 'cnc_manufacturing',
    canonical: 'CNC Machining & CAM',
    category: 'core_engineering',
    aliases: ['CNC', 'G-Code', 'CAM', 'Mastercam', '3D Printing', 'Additive Manufacturing'],
    weight: 4,
  },
  {
    id: 'staad_pro',
    canonical: 'STAAD.Pro / ETABS (Structural Analysis)',
    category: 'core_engineering',
    aliases: ['STAAD.Pro', 'STAAD Pro', 'ETABS', 'SAP2000', 'Structural Analysis'],
    weight: 5,
  },
  {
    id: 'revit_bim',
    canonical: 'Autodesk Revit / BIM',
    category: 'core_engineering',
    aliases: ['Revit', 'Autodesk Revit', 'BIM', 'Building Information Modeling'],
    weight: 4,
  },
  {
    id: 'civil_3d',
    canonical: 'Civil 3D & GIS',
    category: 'core_engineering',
    aliases: ['Civil 3D', 'AutoCAD Civil 3D', 'GIS', 'ArcGIS', 'QGIS'],
    weight: 4,
  },
  {
    id: 'project_planning_eng',
    canonical: 'Project Planning (Primavera / MS Project)',
    category: 'core_engineering',
    aliases: ['Primavera', 'Primavera P6', 'MS Project', 'Microsoft Project', 'CPM Scheduling'],
    weight: 4,
  },
  {
    id: 'six_sigma_lean',
    canonical: 'Lean Manufacturing & Six Sigma',
    category: 'core_engineering',
    aliases: ['Six Sigma', 'Lean Manufacturing', 'Kaizen', '5S', 'DMAIC', 'Green Belt', 'Black Belt'],
    weight: 4,
  },
];
