import { TaxonomySkill } from './types';

export const DATA_ML_AI: TaxonomySkill[] = [
  {
    id: 'machine_learning',
    canonical: 'Machine Learning',
    category: 'data_ml',
    aliases: ['Machine Learning', 'ML', 'Supervised Learning', 'Unsupervised Learning', 'Statistical Learning'],
    weight: 5,
  },
  {
    id: 'deep_learning',
    canonical: 'Deep Learning',
    category: 'data_ml',
    aliases: ['Deep Learning', 'Neural Networks', 'ANN', 'CNN', 'RNN', 'LSTM'],
    implies: ['machine_learning'],
    weight: 5,
  },
  {
    id: 'pytorch',
    canonical: 'PyTorch',
    category: 'data_ml',
    aliases: ['PyTorch', 'Torch'],
    implies: ['python', 'deep_learning'],
    substitutes: [{ id: 'tensorflow', similarity: 0.8 }],
    weight: 5,
  },
  {
    id: 'tensorflow',
    canonical: 'TensorFlow',
    category: 'data_ml',
    aliases: ['TensorFlow', 'Keras', 'TF'],
    implies: ['python', 'deep_learning'],
    substitutes: [{ id: 'pytorch', similarity: 0.8 }],
    weight: 5,
  },
  {
    id: 'scikit_learn',
    canonical: 'Scikit-learn',
    category: 'data_ml',
    aliases: ['Scikit-learn', 'sklearn', 'Scikit Learn'],
    implies: ['python', 'machine_learning'],
    weight: 5,
  },
  {
    id: 'xgboost',
    canonical: 'XGBoost / LightGBM',
    category: 'data_ml',
    aliases: ['XGBoost', 'LightGBM', 'CatBoost', 'Gradient Boosting'],
    implies: ['machine_learning'],
    weight: 4,
  },
  {
    id: 'transformers_hf',
    canonical: 'Hugging Face Transformers',
    category: 'data_ml',
    aliases: ['Hugging Face', 'Transformers', 'HuggingFace', 'BERT', 'RoBERTa'],
    implies: ['deep_learning', 'nlp'],
    weight: 5,
  },
  {
    id: 'llms',
    canonical: 'Large Language Models (LLMs)',
    category: 'data_ml',
    aliases: ['LLMs', 'Large Language Models', 'Generative AI', 'GenAI', 'GPT-4', 'Claude'],
    implies: ['deep_learning'],
    weight: 5,
  },
  {
    id: 'langchain',
    canonical: 'LangChain / LlamaIndex',
    category: 'data_ml',
    aliases: ['LangChain', 'LlamaIndex', 'LangGraph', 'AI Agents'],
    implies: ['llms', 'python'],
    weight: 5,
  },
  {
    id: 'rag',
    canonical: 'Retrieval Augmented Generation (RAG)',
    category: 'data_ml',
    aliases: ['RAG', 'Retrieval Augmented Generation', 'Semantic Search', 'Vector Search'],
    implies: ['llms'],
    weight: 5,
  },
  {
    id: 'vector_databases',
    canonical: 'Vector Databases',
    category: 'data_ml',
    aliases: ['Pinecone', 'Milvus', 'Weaviate', 'Qdrant', 'ChromaDB', 'FAISS', 'pgvector'],
    implies: ['rag'],
    weight: 4,
  },
  {
    id: 'nlp',
    canonical: 'Natural Language Processing (NLP)',
    category: 'data_ml',
    aliases: ['NLP', 'Natural Language Processing', 'Text Mining', 'Named Entity Recognition', 'spaCy', 'NLTK'],
    implies: ['machine_learning'],
    weight: 5,
  },
  {
    id: 'computer_vision',
    canonical: 'Computer Vision',
    category: 'data_ml',
    aliases: ['Computer Vision', 'CV', 'OpenCV', 'YOLO', 'Image Segmentation', 'Object Detection'],
    implies: ['deep_learning'],
    weight: 5,
  },
  {
    id: 'mlops',
    canonical: 'MLOps',
    category: 'data_ml',
    aliases: ['MLOps', 'MLflow', 'Kubeflow', 'Weights & Biases', 'W&B', 'Model Deployment', 'Triton'],
    implies: ['machine_learning'],
    weight: 5,
  },
  {
    id: 'pandas_numpy',
    canonical: 'Pandas & NumPy',
    category: 'data_ml',
    aliases: ['Pandas', 'NumPy', 'DataFrames', 'SciPy'],
    implies: ['python'],
    weight: 5,
  },
  {
    id: 'data_visualization_py',
    canonical: 'Data Visualization (Python)',
    category: 'data_ml',
    aliases: ['Matplotlib', 'Seaborn', 'Plotly'],
    implies: ['python'],
    weight: 4,
  },
  {
    id: 'statistical_analysis',
    canonical: 'Statistical Analysis & A/B Testing',
    category: 'data_ml',
    aliases: ['Statistics', 'A/B Testing', 'Hypothesis Testing', 'Experimentation', 'Statistical Inference'],
    weight: 4,
  },
  {
    id: 'feature_engineering',
    canonical: 'Feature Engineering',
    category: 'data_ml',
    aliases: ['Feature Engineering', 'Feature Selection', 'Dimensionality Reduction', 'PCA'],
    implies: ['machine_learning'],
    weight: 4,
  },
  {
    id: 'recommendation_systems',
    canonical: 'Recommendation Systems',
    category: 'data_ml',
    aliases: ['Recommendation Systems', 'Collaborative Filtering', 'Recommender Systems'],
    implies: ['machine_learning'],
    weight: 4,
  },
  {
    id: 'time_series',
    canonical: 'Time Series Forecasting',
    category: 'data_ml',
    aliases: ['Time Series', 'ARIMA', 'Prophet', 'Forecasting'],
    implies: ['machine_learning'],
    weight: 4,
  },
  {
    id: 'bi_visualization',
    canonical: 'Business Intelligence & Visualization',
    category: 'data_ml',
    aliases: ['Power BI', 'PowerBI', 'Tableau', 'Looker', 'QuickSight', 'Metabase'],
    weight: 4,
  },
];
