import { TaxonomySkill } from './types';

export const DATABASES_DATA: TaxonomySkill[] = [
  {
    id: 'postgresql',
    canonical: 'PostgreSQL',
    category: 'databases',
    aliases: ['PostgreSQL', 'Postgres', 'PGSQL', 'PostgresDB'],
    implies: ['sql'],
    substitutes: [{ id: 'mysql', similarity: 0.75 }, { id: 'oracle_db', similarity: 0.6 }],
    weight: 5,
  },
  {
    id: 'mysql',
    canonical: 'MySQL',
    category: 'databases',
    aliases: ['MySQL', 'MariaDB'],
    implies: ['sql'],
    substitutes: [{ id: 'postgresql', similarity: 0.75 }],
    weight: 5,
  },
  {
    id: 'mongodb',
    canonical: 'MongoDB',
    category: 'databases',
    aliases: ['MongoDB', 'Mongo', 'DocumentDB'],
    substitutes: [{ id: 'dynamodb', similarity: 0.7 }, { id: 'couchdb', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'redis',
    canonical: 'Redis',
    category: 'databases',
    aliases: ['Redis', 'Redis Sentinel', 'Redis Cluster', 'Key-Value Store'],
    substitutes: [{ id: 'memcached', similarity: 0.8 }],
    weight: 5,
  },
  {
    id: 'memcached',
    canonical: 'Memcached',
    category: 'databases',
    aliases: ['Memcached'],
    substitutes: [{ id: 'redis', similarity: 0.8 }],
    weight: 3,
  },
  {
    id: 'elasticsearch',
    canonical: 'Elasticsearch',
    category: 'databases',
    aliases: ['Elasticsearch', 'Elastic Search', 'OpenSearch', 'ELK'],
    substitutes: [{ id: 'opensearch', similarity: 0.95 }, { id: 'solr', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'opensearch',
    canonical: 'OpenSearch',
    category: 'databases',
    aliases: ['OpenSearch', 'AWS OpenSearch'],
    substitutes: [{ id: 'elasticsearch', similarity: 0.95 }],
    weight: 4,
  },
  {
    id: 'dynamodb',
    canonical: 'Amazon DynamoDB',
    category: 'databases',
    aliases: ['DynamoDB', 'Amazon DynamoDB', 'AWS DynamoDB'],
    substitutes: [{ id: 'mongodb', similarity: 0.7 }, { id: 'cassandra', similarity: 0.6 }],
    weight: 4,
  },
  {
    id: 'cassandra',
    canonical: 'Apache Cassandra',
    category: 'databases',
    aliases: ['Cassandra', 'Apache Cassandra', 'ScyllaDB'],
    substitutes: [{ id: 'dynamodb', similarity: 0.6 }],
    weight: 4,
  },
  {
    id: 'sqlite',
    canonical: 'SQLite',
    category: 'databases',
    aliases: ['SQLite', 'SQLite3'],
    implies: ['sql'],
    weight: 3,
  },
  {
    id: 'oracle_db',
    canonical: 'Oracle Database',
    category: 'databases',
    aliases: ['Oracle Database', 'Oracle DB', 'Oracle RDBMS', 'Oracle 19c'],
    implies: ['sql', 'plsql'],
    substitutes: [{ id: 'postgresql', similarity: 0.6 }, { id: 'sql_server', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'sql_server',
    canonical: 'Microsoft SQL Server',
    category: 'databases',
    aliases: ['SQL Server', 'Microsoft SQL Server', 'MSSQL', 'T-SQL'],
    implies: ['sql'],
    substitutes: [{ id: 'oracle_db', similarity: 0.7 }, { id: 'postgresql', similarity: 0.65 }],
    weight: 4,
  },
  {
    id: 'cockroachdb',
    canonical: 'CockroachDB',
    category: 'databases',
    aliases: ['CockroachDB', 'Distributed SQL'],
    implies: ['sql'],
    substitutes: [{ id: 'postgresql', similarity: 0.8 }],
    weight: 4,
  },
  {
    id: 'neo4j',
    canonical: 'Neo4j',
    category: 'databases',
    aliases: ['Neo4j', 'Graph Database', 'Cypher Query Language'],
    weight: 3,
  },
  {
    id: 'timescaledb',
    canonical: 'TimescaleDB / InfluxDB',
    category: 'databases',
    aliases: ['TimescaleDB', 'InfluxDB', 'Time Series Database', 'TSDB'],
    weight: 3,
  },
  {
    id: 'clickhouse',
    canonical: 'ClickHouse',
    category: 'databases',
    aliases: ['ClickHouse', 'Columnar Database'],
    substitutes: [{ id: 'snowflake', similarity: 0.6 }, { id: 'bigquery', similarity: 0.6 }],
    weight: 4,
  },
  {
    id: 'snowflake',
    canonical: 'Snowflake',
    category: 'databases',
    aliases: ['Snowflake', 'Snowflake Data Cloud', 'SnowSQL'],
    substitutes: [{ id: 'bigquery', similarity: 0.8 }, { id: 'redshift', similarity: 0.75 }, { id: 'databricks', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'bigquery',
    canonical: 'Google BigQuery',
    category: 'databases',
    aliases: ['BigQuery', 'Google BigQuery', 'GCP BigQuery'],
    substitutes: [{ id: 'snowflake', similarity: 0.8 }, { id: 'redshift', similarity: 0.75 }],
    weight: 5,
  },
  {
    id: 'redshift',
    canonical: 'Amazon Redshift',
    category: 'databases',
    aliases: ['Redshift', 'Amazon Redshift', 'AWS Redshift'],
    substitutes: [{ id: 'snowflake', similarity: 0.75 }, { id: 'bigquery', similarity: 0.75 }],
    weight: 4,
  },
  {
    id: 'databricks',
    canonical: 'Databricks',
    category: 'databases',
    aliases: ['Databricks', 'Delta Lake', 'Lakehouse'],
    implies: ['apache_spark'],
    substitutes: [{ id: 'snowflake', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'apache_spark',
    canonical: 'Apache Spark',
    category: 'databases',
    aliases: ['Apache Spark', 'Spark', 'PySpark', 'Spark SQL', 'Spark Streaming'],
    weight: 5,
  },
  {
    id: 'kafka',
    canonical: 'Kafka',
    category: 'databases',
    aliases: ['Kafka', 'Apache Kafka', 'Kafka Streams', 'Kafka Connect'],
    substitutes: [{ id: 'rabbitmq', similarity: 0.5 }, { id: 'apache_pulsar', similarity: 0.75 }],
    weight: 5,
  },
  {
    id: 'rabbitmq',
    canonical: 'RabbitMQ',
    category: 'databases',
    aliases: ['RabbitMQ', 'AMQP'],
    substitutes: [{ id: 'apache_kafka', similarity: 0.5 }, { id: 'activemq', similarity: 0.8 }],
    weight: 4,
  },
  {
    id: 'apache_flink',
    canonical: 'Apache Flink',
    category: 'databases',
    aliases: ['Apache Flink', 'Flink'],
    substitutes: [{ id: 'apache_spark', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'dbt',
    canonical: 'dbt (data build tool)',
    category: 'databases',
    aliases: ['dbt', 'dbt Core', 'dbt Cloud'],
    implies: ['sql'],
    weight: 4,
  },
  {
    id: 'apache_airflow',
    canonical: 'Apache Airflow',
    category: 'databases',
    aliases: ['Airflow', 'Apache Airflow', 'Workflow Orchestration'],
    implies: ['python'],
    substitutes: [{ id: 'prefect', similarity: 0.75 }, { id: 'dagster', similarity: 0.75 }],
    weight: 5,
  },
  {
    id: 'etl_pipelines',
    canonical: 'ETL / ELT Pipelines',
    category: 'databases',
    aliases: ['ETL', 'ELT', 'Data Pipeline', 'Data Ingestion', 'Batch Processing'],
    weight: 5,
  },
  {
    id: 'data_modeling',
    canonical: 'Data Modeling',
    category: 'databases',
    aliases: ['Data Modeling', 'Star Schema', 'Snowflake Schema', 'Dimensional Modeling', 'Normalization'],
    weight: 4,
  },
  {
    id: 'change_data_capture',
    canonical: 'Change Data Capture (CDC)',
    category: 'databases',
    aliases: ['CDC', 'Change Data Capture', 'Debezium'],
    weight: 3,
  },
];
