import { TaxonomySkill } from './types';

export const FRONTEND_WEB: TaxonomySkill[] = [
  {
    id: 'react',
    canonical: 'React',
    category: 'frontend',
    aliases: ['React', 'React.js', 'ReactJS'],
    implies: ['javascript'],
    substitutes: [{ id: 'vue', similarity: 0.6 }, { id: 'angular', similarity: 0.5 }],
    weight: 5,
  },
  {
    id: 'next_js',
    canonical: 'Next.js',
    category: 'frontend',
    aliases: ['Next.js', 'NextJS', 'Next 13', 'Next 14', 'Next 15'],
    implies: ['react', 'javascript'],
    substitutes: [{ id: 'remix', similarity: 0.75 }, { id: 'nuxtjs', similarity: 0.6 }],
    weight: 5,
  },
  {
    id: 'vue',
    canonical: 'Vue.js',
    category: 'frontend',
    aliases: ['Vue', 'Vue.js', 'VueJS', 'Vue 3', 'Vue 2'],
    implies: ['javascript'],
    substitutes: [{ id: 'react', similarity: 0.6 }, { id: 'angular', similarity: 0.5 }],
    weight: 5,
  },
  {
    id: 'nuxtjs',
    canonical: 'Nuxt.js',
    category: 'frontend',
    aliases: ['Nuxt', 'Nuxt.js', 'NuxtJS', 'Nuxt 3'],
    implies: ['vue', 'javascript'],
    substitutes: [{ id: 'nextjs', similarity: 0.65 }],
    weight: 4,
  },
  {
    id: 'angular',
    canonical: 'Angular',
    category: 'frontend',
    aliases: ['Angular', 'Angular 2+', 'AngularJS', 'Angular 14', 'Angular 15', 'Angular 16', 'Angular 17'],
    implies: ['typescript', 'javascript'],
    substitutes: [{ id: 'react', similarity: 0.5 }, { id: 'vue', similarity: 0.5 }],
    weight: 5,
  },
  {
    id: 'svelte',
    canonical: 'Svelte',
    category: 'frontend',
    aliases: ['Svelte', 'SvelteKit'],
    implies: ['javascript'],
    substitutes: [{ id: 'vue', similarity: 0.6 }, { id: 'react', similarity: 0.5 }],
    weight: 4,
  },
  {
    id: 'remix',
    canonical: 'Remix',
    category: 'frontend',
    aliases: ['Remix', 'Remix Run'],
    implies: ['react', 'javascript'],
    substitutes: [{ id: 'nextjs', similarity: 0.75 }],
    weight: 4,
  },
  {
    id: 'astro',
    canonical: 'Astro',
    category: 'frontend',
    aliases: ['Astro', 'Astro.build'],
    weight: 3,
  },
  {
    id: 'solidjs',
    canonical: 'SolidJS',
    category: 'frontend',
    aliases: ['SolidJS', 'Solid.js'],
    implies: ['javascript'],
    weight: 3,
  },
  {
    id: 'redux',
    canonical: 'Redux',
    category: 'frontend',
    aliases: ['Redux', 'Redux Toolkit', 'RTK', 'Redux Saga', 'Redux Thunk'],
    implies: ['react', 'javascript'],
    substitutes: [{ id: 'zustand', similarity: 0.8 }, { id: 'mobx', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'zustand',
    canonical: 'Zustand',
    category: 'frontend',
    aliases: ['Zustand'],
    implies: ['react'],
    substitutes: [{ id: 'redux', similarity: 0.8 }],
    weight: 4,
  },
  {
    id: 'mobx',
    canonical: 'MobX',
    category: 'frontend',
    aliases: ['MobX', 'MobX-State-Tree'],
    weight: 3,
  },
  {
    id: 'tanstack_query',
    canonical: 'TanStack Query',
    category: 'frontend',
    aliases: ['TanStack Query', 'React Query', 'React-Query'],
    implies: ['react'],
    substitutes: [{ id: 'swr', similarity: 0.85 }],
    weight: 4,
  },
  {
    id: 'swr',
    canonical: 'SWR',
    category: 'frontend',
    aliases: ['SWR'],
    implies: ['react'],
    substitutes: [{ id: 'tanstack_query', similarity: 0.85 }],
    weight: 3,
  },
  {
    id: 'rxjs',
    canonical: 'RxJS',
    category: 'frontend',
    aliases: ['RxJS'],
    implies: ['javascript'],
    weight: 3,
  },
  {
    id: 'tailwind_css',
    canonical: 'Tailwind CSS',
    category: 'frontend',
    aliases: ['Tailwind', 'Tailwind CSS', 'TailwindCSS'],
    implies: ['css'],
    substitutes: [{ id: 'bootstrap', similarity: 0.5 }],
    weight: 4,
  },
  {
    id: 'bootstrap',
    canonical: 'Bootstrap',
    category: 'frontend',
    aliases: ['Bootstrap', 'Bootstrap 5', 'Twitter Bootstrap'],
    implies: ['css'],
    substitutes: [{ id: 'tailwind_css', similarity: 0.5 }],
    weight: 3,
  },
  {
    id: 'material_ui',
    canonical: 'Material UI (MUI)',
    category: 'frontend',
    aliases: ['Material-UI', 'MUI', 'Material UI'],
    implies: ['react'],
    substitutes: [{ id: 'chakra_ui', similarity: 0.7 }, { id: 'ant_design', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'chakra_ui',
    canonical: 'Chakra UI',
    category: 'frontend',
    aliases: ['Chakra UI', 'ChakraUI'],
    implies: ['react'],
    weight: 3,
  },
  {
    id: 'shadcn_ui',
    canonical: 'Shadcn UI',
    category: 'frontend',
    aliases: ['shadcn', 'shadcn/ui', 'Radix UI'],
    implies: ['react', 'tailwind_css'],
    weight: 4,
  },
  {
    id: 'ant_design',
    canonical: 'Ant Design',
    category: 'frontend',
    aliases: ['Ant Design', 'AntD'],
    implies: ['react'],
    weight: 3,
  },
  {
    id: 'styled_components',
    canonical: 'Styled Components',
    category: 'frontend',
    aliases: ['styled-components', 'CSS-in-JS', 'Emotion'],
    implies: ['css', 'react'],
    weight: 3,
  },
  {
    id: 'webpack',
    canonical: 'Webpack',
    category: 'frontend',
    aliases: ['Webpack', 'Webpack 5'],
    substitutes: [{ id: 'vite', similarity: 0.75 }, { id: 'rollup', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'vite',
    canonical: 'Vite',
    category: 'frontend',
    aliases: ['Vite', 'ViteJS'],
    substitutes: [{ id: 'webpack', similarity: 0.75 }],
    weight: 4,
  },
  {
    id: 'rollup',
    canonical: 'Rollup',
    category: 'frontend',
    aliases: ['Rollup', 'Rollup.js'],
    weight: 3,
  },
  {
    id: 'babel',
    canonical: 'Babel',
    category: 'frontend',
    aliases: ['Babel', 'Babel.js'],
    weight: 3,
  },
  {
    id: 'responsive_design',
    canonical: 'Responsive Web Design',
    category: 'frontend',
    aliases: ['Responsive Design', 'Mobile-First Design', 'Flexbox', 'CSS Grid', 'Media Queries'],
    implies: ['css'],
    weight: 4,
  },
  {
    id: 'web_accessibility',
    canonical: 'Web Accessibility (a11y)',
    category: 'frontend',
    aliases: ['Accessibility', 'a11y', 'WCAG', 'ARIA', 'Screen Readers'],
    weight: 4,
  },
  {
    id: 'webrtc',
    canonical: 'WebRTC',
    category: 'frontend',
    aliases: ['WebRTC', 'Real-Time Audio Video'],
    weight: 3,
  },
  {
    id: 'pwa',
    canonical: 'Progressive Web Apps (PWA)',
    category: 'frontend',
    aliases: ['PWA', 'Progressive Web App', 'Service Workers'],
    weight: 3,
  },
  {
    id: 'threejs',
    canonical: 'Three.js / WebGL',
    category: 'frontend',
    aliases: ['Three.js', 'ThreeJS', 'WebGL', '3D Web'],
    weight: 3,
  },
  {
    id: 'd3js',
    canonical: 'D3.js',
    category: 'frontend',
    aliases: ['D3.js', 'D3', 'Data-Driven Documents'],
    weight: 4,
  },
  {
    id: 'chartjs_recharts',
    canonical: 'Data Visualization Libraries',
    category: 'frontend',
    aliases: ['Recharts', 'Chart.js', 'ECharts', 'Highcharts'],
    weight: 3,
  },
  {
    id: 'storybook',
    canonical: 'Storybook',
    category: 'frontend',
    aliases: ['Storybook', 'Storybook.js'],
    weight: 3,
  },
  {
    id: 'playwright',
    canonical: 'Playwright',
    category: 'frontend',
    aliases: ['Playwright'],
    substitutes: [{ id: 'cypress', similarity: 0.8 }, { id: 'selenium', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'cypress',
    canonical: 'Cypress',
    category: 'frontend',
    aliases: ['Cypress', 'Cypress.io'],
    substitutes: [{ id: 'playwright', similarity: 0.8 }],
    weight: 4,
  },
  {
    id: 'jest',
    canonical: 'Jest',
    category: 'frontend',
    aliases: ['Jest', 'Jest.js'],
    substitutes: [{ id: 'vitest', similarity: 0.85 }],
    weight: 4,
  },
  {
    id: 'vitest',
    canonical: 'Vitest',
    category: 'frontend',
    aliases: ['Vitest'],
    substitutes: [{ id: 'jest', similarity: 0.85 }],
    weight: 4,
  },
  {
    id: 'react_testing_library',
    canonical: 'Testing Library',
    category: 'frontend',
    aliases: ['Testing Library', 'React Testing Library', 'RTL'],
    implies: ['react'],
    weight: 4,
  },
  {
    id: 'microfrontends',
    canonical: 'Microfrontends',
    category: 'frontend',
    aliases: ['Micro Frontends', 'Microfrontends', 'Module Federation', 'Single-SPA'],
    weight: 4,
  },
  {
    id: 'web_performance',
    canonical: 'Web Performance Optimization',
    category: 'frontend',
    aliases: ['Web Performance', 'Core Web Vitals', 'Lighthouse', 'LCP', 'CLS', 'FID'],
    weight: 4,
  },
  {
    id: 'jquery',
    canonical: 'jQuery',
    category: 'frontend',
    aliases: ['jQuery'],
    weight: 2,
  },
];
