import { TaxonomySkill } from './types';

export const MOBILE_SECURITY_EMBEDDED: TaxonomySkill[] = [
  {
    id: 'ios_development',
    canonical: 'iOS Development',
    category: 'mobile',
    aliases: ['iOS', 'iOS Development', 'SwiftUI', 'UIKit', 'Cocoa Touch', 'Xcode'],
    implies: ['swift'],
    weight: 5,
  },
  {
    id: 'android_development',
    canonical: 'Android Development',
    category: 'mobile',
    aliases: ['Android', 'Android Development', 'Android SDK', 'Jetpack Compose', 'Android Studio'],
    implies: ['kotlin'],
    weight: 5,
  },
  {
    id: 'react_native',
    canonical: 'React Native',
    category: 'mobile',
    aliases: ['React Native', 'RN', 'Expo'],
    implies: ['react', 'javascript'],
    substitutes: [{ id: 'flutter', similarity: 0.75 }],
    weight: 5,
  },
  {
    id: 'flutter',
    canonical: 'Flutter',
    category: 'mobile',
    aliases: ['Flutter', 'Flutter SDK'],
    implies: ['dart'],
    substitutes: [{ id: 'react_native', similarity: 0.75 }],
    weight: 5,
  },
  {
    id: 'mobile_cicd',
    canonical: 'Mobile CI/CD',
    category: 'mobile',
    aliases: ['Fastlane', 'TestFlight', 'Google Play Console', 'App Store Connect'],
    weight: 3,
  },
  {
    id: 'cybersecurity',
    canonical: 'Cybersecurity',
    category: 'security',
    aliases: ['Cybersecurity', 'Information Security', 'InfoSec', 'Security Operations', 'SecOps'],
    weight: 5,
  },
  {
    id: 'application_security',
    canonical: 'Application Security (AppSec)',
    category: 'security',
    aliases: ['AppSec', 'Application Security', 'OWASP', 'OWASP Top 10', 'SAST', 'DAST'],
    weight: 5,
  },
  {
    id: 'penetration_testing',
    canonical: 'Penetration Testing',
    category: 'security',
    aliases: ['Penetration Testing', 'Pen Testing', 'Ethical Hacking', 'Vulnerability Assessment', 'Bug Bounty'],
    weight: 4,
  },
  {
    id: 'security_tools',
    canonical: 'Security Assessment Tools',
    category: 'security',
    aliases: ['Burp Suite', 'Wireshark', 'Metasploit', 'Nmap', 'Nessus', 'Kali Linux'],
    weight: 4,
  },
  {
    id: 'cryptography',
    canonical: 'Cryptography & PKI',
    category: 'security',
    aliases: ['Cryptography', 'PKI', 'Public Key Infrastructure', 'TLS', 'SSL', 'Encryption', 'AES', 'RSA'],
    weight: 4,
  },
  {
    id: 'network_security',
    canonical: 'Network Security',
    category: 'security',
    aliases: ['Network Security', 'Firewalls', 'VPN', 'IDS', 'IPS', 'Zero Trust Architecture'],
    weight: 4,
  },
  {
    id: 'embedded_c',
    canonical: 'Embedded C / C++',
    category: 'embedded',
    aliases: ['Embedded C', 'Embedded C++', 'Firmware', 'Firmware Development', 'Bare Metal'],
    implies: ['c'],
    weight: 5,
  },
  {
    id: 'microcontrollers',
    canonical: 'Microcontrollers & Architecture',
    category: 'embedded',
    aliases: ['Microcontrollers', 'MCU', 'ARM Cortex', 'STM32', 'ESP32', 'Arduino', 'Raspberry Pi', 'AVR', 'PIC'],
    weight: 5,
  },
  {
    id: 'rtos',
    canonical: 'Real-Time Operating Systems (RTOS)',
    category: 'embedded',
    aliases: ['RTOS', 'FreeRTOS', 'Zephyr', 'Embedded Linux'],
    weight: 5,
  },
  {
    id: 'hardware_protocols',
    canonical: 'Hardware Communication Protocols',
    category: 'embedded',
    aliases: ['I2C', 'SPI', 'UART', 'CAN Bus', 'CAN', 'RS-485', 'RS-232', 'Modbus'],
    weight: 4,
  },
  {
    id: 'iot',
    canonical: 'Internet of Things (IoT)',
    category: 'embedded',
    aliases: ['IoT', 'Internet of Things', 'MQTT', 'CoAP', 'BLE', 'Bluetooth Low Energy', 'Zigbee'],
    weight: 4,
  },
  {
    id: 'device_drivers',
    canonical: 'Device Drivers',
    category: 'embedded',
    aliases: ['Device Drivers', 'Linux Kernel Drivers', 'BSP', 'Board Support Package'],
    weight: 4,
  },
  {
    id: 'pcb_design',
    canonical: 'PCB Design & Hardware Debugging',
    category: 'embedded',
    aliases: ['PCB Design', 'KiCAD', 'Altium Designer', 'Eagle', 'Oscilloscope', 'Logic Analyzer'],
    weight: 3,
  },
];
