import { TaxonomySkill } from './types';

export const SOFTWARE_LANGUAGES: TaxonomySkill[] = [
  {
    id: 'python',
    canonical: 'Python',
    category: 'languages',
    aliases: ['Python', 'Python3', 'Python2', 'Py'],
    substitutes: [{ id: 'ruby', similarity: 0.5 }, { id: 'javascript', similarity: 0.4 }],
    weight: 5,
  },
  {
    id: 'javascript',
    canonical: 'JavaScript',
    category: 'languages',
    aliases: ['JavaScript', 'JS', 'ECMAScript', 'ES6', 'ES2015', 'ES2020'],
    implies: ['web_fundamentals'],
    substitutes: [{ id: 'typescript', similarity: 0.85 }],
    weight: 5,
  },
  {
    id: 'typescript',
    canonical: 'TypeScript',
    category: 'languages',
    aliases: ['TypeScript', 'TS'],
    implies: ['javascript'],
    substitutes: [{ id: 'javascript', similarity: 0.85 }],
    weight: 5,
  },
  {
    id: 'java',
    canonical: 'Java',
    category: 'languages',
    aliases: ['Java', 'Java 8', 'Java 11', 'Java 17', 'Java 21', 'Core Java', 'J2EE'],
    substitutes: [{ id: 'kotlin', similarity: 0.75 }, { id: 'csharp', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'c',
    canonical: 'C',
    category: 'languages',
    aliases: ['C', 'C language', 'ANSI C', 'C99', 'C11'],
    ambiguous: true,
    contextHints: ['programming', 'c/c++', 'language', 'developer', 'embedded', 'software', 'pointer', 'memory', 'compiler', 'systems'],
    substitutes: [{ id: 'cpp', similarity: 0.7 }],
    weight: 4,
  },
  {
    id: 'cpp',
    canonical: 'C++',
    category: 'languages',
    aliases: ['C++', 'CPP', 'C++11', 'C++14', 'C++17', 'C++20'],
    implies: ['c'],
    substitutes: [{ id: 'c', similarity: 0.7 }, { id: 'rust', similarity: 0.6 }],
    weight: 5,
  },
  {
    id: 'csharp',
    canonical: 'C#',
    category: 'languages',
    aliases: ['C#', 'CSharp', 'C Sharp', '.NET C#'],
    substitutes: [{ id: 'java', similarity: 0.7 }],
    weight: 5,
  },
  {
    id: 'go',
    canonical: 'Go',
    category: 'languages',
    aliases: ['Go', 'Golang'],
    ambiguous: true,
    contextHints: ['golang', 'language', 'concurrency', 'backend', 'developer', 'goroutine', 'microservice', 'channel'],
    substitutes: [{ id: 'rust', similarity: 0.5 }, { id: 'java', similarity: 0.5 }],
    weight: 5,
  },
  {
    id: 'rust',
    canonical: 'Rust',
    category: 'languages',
    aliases: ['Rust', 'Rustlang'],
    ambiguous: true,
    contextHints: ['rust lang', 'rust programming', 'cargo', 'borrow checker', 'systems programming', 'memory safety', 'developer'],
    substitutes: [{ id: 'cpp', similarity: 0.6 }, { id: 'go', similarity: 0.5 }],
    weight: 5,
  },
  {
    id: 'ruby',
    canonical: 'Ruby',
    category: 'languages',
    aliases: ['Ruby'],
    substitutes: [{ id: 'python', similarity: 0.5 }],
    weight: 4,
  },
  {
    id: 'php',
    canonical: 'PHP',
    category: 'languages',
    aliases: ['PHP', 'PHP7', 'PHP8'],
    weight: 4,
  },
  {
    id: 'swift',
    canonical: 'Swift',
    category: 'languages',
    aliases: ['Swift'],
    ambiguous: true,
    contextHints: ['swift lang', 'ios', 'apple', 'xcode', 'swiftui', 'uikit', 'cocoa', 'developer'],
    substitutes: [{ id: 'kotlin', similarity: 0.6 }],
    weight: 5,
  },
  {
    id: 'kotlin',
    canonical: 'Kotlin',
    category: 'languages',
    aliases: ['Kotlin'],
    substitutes: [{ id: 'java', similarity: 0.75 }, { id: 'swift', similarity: 0.6 }],
    weight: 5,
  },
  {
    id: 'scala',
    canonical: 'Scala',
    category: 'languages',
    aliases: ['Scala'],
    substitutes: [{ id: 'java', similarity: 0.65 }],
    weight: 4,
  },
  {
    id: 'r',
    canonical: 'R',
    category: 'languages',
    aliases: ['R', 'R language', 'R-project'],
    ambiguous: true,
    contextHints: ['r language', 'r programming', 'statistics', 'data analysis', 'ggplot', 'bioconductor', 'r studio', 'stats'],
    substitutes: [{ id: 'python', similarity: 0.6 }],
    weight: 4,
  },
  {
    id: 'dart',
    canonical: 'Dart',
    category: 'languages',
    aliases: ['Dart'],
    substitutes: [{ id: 'typescript', similarity: 0.5 }],
    weight: 4,
  },
  {
    id: 'elixir',
    canonical: 'Elixir',
    category: 'languages',
    aliases: ['Elixir'],
    substitutes: [{ id: 'erlang', similarity: 0.8 }],
    weight: 4,
  },
  {
    id: 'erlang',
    canonical: 'Erlang',
    category: 'languages',
    aliases: ['Erlang'],
    weight: 3,
  },
  {
    id: 'clojure',
    canonical: 'Clojure',
    category: 'languages',
    aliases: ['Clojure'],
    weight: 3,
  },
  {
    id: 'haskell',
    canonical: 'Haskell',
    category: 'languages',
    aliases: ['Haskell'],
    weight: 3,
  },
  {
    id: 'lua',
    canonical: 'Lua',
    category: 'languages',
    aliases: ['Lua'],
    weight: 3,
  },
  {
    id: 'perl',
    canonical: 'Perl',
    category: 'languages',
    aliases: ['Perl', 'Perl 5'],
    weight: 3,
  },
  {
    id: 'bash',
    canonical: 'Bash / Shell',
    category: 'languages',
    aliases: ['Bash', 'Shell', 'Shell Scripting', 'Zsh', 'sh'],
    weight: 4,
  },
  {
    id: 'powershell',
    canonical: 'PowerShell',
    category: 'languages',
    aliases: ['PowerShell', 'pwsh'],
    weight: 3,
  },
  {
    id: 'sql',
    canonical: 'SQL',
    category: 'languages',
    aliases: ['SQL', 'Structured Query Language', 'ANSI SQL'],
    weight: 5,
  },
  {
    id: 'plsql',
    canonical: 'PL/SQL',
    category: 'languages',
    aliases: ['PL/SQL', 'PLSQL', 'T-SQL', 'Transact-SQL'],
    implies: ['sql'],
    weight: 4,
  },
  {
    id: 'solidity',
    canonical: 'Solidity',
    category: 'languages',
    aliases: ['Solidity', 'Smart Contracts'],
    weight: 3,
  },
  {
    id: 'objective_c',
    canonical: 'Objective-C',
    category: 'languages',
    aliases: ['Objective-C', 'Obj-C', 'Objective C'],
    substitutes: [{ id: 'swift', similarity: 0.6 }],
    weight: 3,
  },
  {
    id: 'assembly',
    canonical: 'Assembly',
    category: 'languages',
    aliases: ['Assembly', 'x86 Assembly', 'ARM Assembly', 'ASM'],
    weight: 3,
  },
  {
    id: 'matlab',
    canonical: 'MATLAB',
    category: 'languages',
    aliases: ['MATLAB', 'Simulink'],
    substitutes: [{ id: 'python', similarity: 0.5 }],
    weight: 4,
  },
  {
    id: 'groovy',
    canonical: 'Groovy',
    category: 'languages',
    aliases: ['Groovy', 'Apache Groovy'],
    weight: 3,
  },
  {
    id: 'julia',
    canonical: 'Julia',
    category: 'languages',
    aliases: ['Julia', 'Julia lang'],
    substitutes: [{ id: 'python', similarity: 0.55 }],
    weight: 3,
  },
  {
    id: 'fsharp',
    canonical: 'F#',
    category: 'languages',
    aliases: ['F#', 'FSharp'],
    weight: 3,
  },
  {
    id: 'ocaml',
    canonical: 'OCaml',
    category: 'languages',
    aliases: ['OCaml'],
    weight: 3,
  },
  {
    id: 'zig',
    canonical: 'Zig',
    category: 'languages',
    aliases: ['Zig', 'Zig lang'],
    substitutes: [{ id: 'c', similarity: 0.6 }, { id: 'rust', similarity: 0.5 }],
    weight: 3,
  },
  {
    id: 'fortran',
    canonical: 'Fortran',
    category: 'languages',
    aliases: ['Fortran', 'FORTRAN 90', 'FORTRAN 77'],
    weight: 2,
  },
  {
    id: 'cobol',
    canonical: 'COBOL',
    category: 'languages',
    aliases: ['COBOL'],
    weight: 2,
  },
  {
    id: 'visual_basic',
    canonical: 'Visual Basic',
    category: 'languages',
    aliases: ['Visual Basic', 'VB.NET', 'VBA'],
    weight: 2,
  },
  {
    id: 'apex',
    canonical: 'Apex',
    category: 'languages',
    aliases: ['Apex', 'Salesforce Apex'],
    weight: 3,
  },
  {
    id: 'sas',
    canonical: 'SAS',
    category: 'languages',
    aliases: ['SAS', 'SAS Programming'],
    weight: 3,
  },
  {
    id: 'abap',
    canonical: 'ABAP',
    category: 'languages',
    aliases: ['ABAP', 'SAP ABAP'],
    weight: 3,
  },
  {
    id: 'vhdl',
    canonical: 'VHDL',
    category: 'languages',
    aliases: ['VHDL'],
    substitutes: [{ id: 'verilog', similarity: 0.8 }],
    weight: 3,
  },
  {
    id: 'verilog',
    canonical: 'Verilog',
    category: 'languages',
    aliases: ['Verilog', 'SystemVerilog'],
    substitutes: [{ id: 'vhdl', similarity: 0.8 }],
    weight: 3,
  },
  {
    id: 'prolog',
    canonical: 'Prolog',
    category: 'languages',
    aliases: ['Prolog'],
    weight: 2,
  },
  {
    id: 'scheme_lisp',
    canonical: 'Lisp / Scheme',
    category: 'languages',
    aliases: ['Lisp', 'Common Lisp', 'Scheme', 'Racket'],
    weight: 2,
  },
  {
    id: 'html',
    canonical: 'HTML5',
    category: 'languages',
    aliases: ['HTML', 'HTML5'],
    weight: 4,
  },
  {
    id: 'css',
    canonical: 'CSS3',
    category: 'languages',
    aliases: ['CSS', 'CSS3'],
    weight: 4,
  },
  {
    id: 'sass_scss',
    canonical: 'Sass / SCSS',
    category: 'languages',
    aliases: ['Sass', 'SCSS', 'Less', 'Stylus'],
    implies: ['css'],
    weight: 3,
  },
  {
    id: 'graphql_lang',
    canonical: 'GraphQL Schema',
    category: 'languages',
    aliases: ['GraphQL SDL'],
    weight: 3,
  },
];
