import { z } from 'zod';
import type { DeterministicFacts, AICommentary, HarshTruthItem, BulletRewriteItem } from './types';

export const SYSTEM_PROMPT = `You are a veteran technical recruiter and staff engineer with 12+ years of hiring experience across global tech giants (Google, Meta, Uber, Stripe), high-growth product unicorns, and Indian enterprise firms.
You are evaluating a candidate's resume against a target Job Description. You deliver the raw, unvarnished hiring truth with tactical precision.

RULES OF ENGAGEMENT:
1. STRICT TRUTHFULNESS & GROUNDING: You MUST NOT invent, hallucinate, or assume technologies, metrics, or responsibilities that the candidate did not mention.
2. HARSH TRUTHS: Each harsh truth must point directly to a real flaw (e.g. passive job descriptions, missing core tech stack, unquantified claims, keyword stuffing, lack of production scale).
3. BULLET REWRITES: Rewrite actual weak bullets from the candidate's resume using the Google XYZ formula: "Accomplished [X] as measured by [Y] by doing [Z]". Do not invent fictional 10x numbers; add realistic metric brackets or show how to frame their real impact.
4. SKILL GAPS: Distinguish between 'wording_fix' (candidate has adjacent experience or synonymous tech) vs 'learn_needed' (genuine missing core competency).
5. RECRUITER 6-SECOND SCAN: Summarize exactly what a recruiter notices in their initial 6-second glance before deciding to reject or advance.
6. JSON ONLY: Return ONLY valid JSON adhering strictly to the required schema.`;

export const AICommentarySchema = z.object({
  verdict: z.object({
    headline: z.string(),
    tone: z.enum(['strong', 'borderline', 'weak']),
    oneParagraphSummary: z.string(),
  }),
  recruiterFirst6Seconds: z.string(),
  harshTruths: z.array(
    z.object({
      severity: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5)]),
      issue: z.string(),
      evidenceQuote: z.string(),
      whyItHurts: z.string(),
      fix: z.string(),
    })
  ),
  skillGaps: z.array(
    z.object({
      skill: z.string(),
      type: z.enum(['wording_fix', 'learn_needed']),
      fastestWayToClose: z.string(),
      estimatedDays: z.number(),
    })
  ),
  bulletRewrites: z.array(
    z.object({
      original: z.string(),
      rewritten: z.string(),
      whatChanged: z.string(),
    })
  ),
  marketPositioning: z.object({
    bestFitTier: z.string(),
    whyNotNextTier: z.string(),
    topThreeSignalsToAdd: z.array(z.string()),
  }),
  interviewRiskQuestions: z.array(
    z.object({
      question: z.string(),
      whyTheyWillAsk: z.string(),
      prepHint: z.string(),
    })
  ),
  sevenDayPlan: z.array(
    z.object({
      day: z.number(),
      task: z.string(),
      outcome: z.string(),
    })
  ),
  thirtyDayPlan: z.array(
    z.object({
      week: z.number(),
      focus: z.string(),
      deliverable: z.string(),
    })
  ),
  alternativeRoles: z.array(
    z.object({
      role: z.string(),
      fitScore: z.number(),
      reason: z.string(),
    })
  ),
});

export function buildAIPrompt(facts: DeterministicFacts, resumeText: string, jdText: string): string {
  const missingMustHaves = facts.skillMatches
    .filter(m => m.importance === 'must_have' && m.status === 'missing')
    .map(m => m.skill);

  const relatedSkills = facts.skillMatches
    .filter(m => m.status === 'related')
    .map(m => `${m.skill} (found related: ${m.evidenceSnippet || 'yes'})`);

  const weakestBullets = [...facts.bulletAnalyses]
    .filter(b => b.score < 65)
    .sort((a, b) => a.score - b.score)
    .slice(0, 4)
    .map(b => `[Score ${b.score}/100]: "${b.rawText}" (Issues: ${b.weakPhrases.join(', ') || 'lack of metrics'})`);

  return `Here is the candidate's resume analysis generated by our deterministic parser:

--- TARGET ROLE & JD CONTEXT ---
Role: ${facts.jd.roleTitle || 'Software Engineer'}
Experience Required: ${facts.seniorityFit.requiredYears ?? 'Not specified'} years
Seniority Match: ${facts.seniorityFit.status} (Candidate has ~${facts.seniorityFit.candidateYears} yrs)

--- DETERMINISTIC SCORES ---
Overall ATS Fit Score: ${facts.scoreBreakdown.finalScore}%
Must-Have Coverage: ${facts.scoreBreakdown.mustHaveCoverageScore}%
Evidence Quality: ${facts.scoreBreakdown.evidenceQualityScore}%
Seniority Fit: ${facts.scoreBreakdown.seniorityFitScore}%
Project Relevance: ${facts.scoreBreakdown.projectRelevanceScore}%
Format Safety: ${facts.scoreBreakdown.formatSafetyScore}%
Keyword Stuffing Penalty: ${facts.scoreBreakdown.keywordStuffingPenalty}

--- SKILL GAP SIGNALS ---
Missing Must-Haves: ${missingMustHaves.length > 0 ? missingMustHaves.join(', ') : 'None'}
Related/Partial Skills: ${relatedSkills.length > 0 ? relatedSkills.join(', ') : 'None'}

--- WEAK BULLETS IDENTIFIED BY ENGINE ---
${weakestBullets.length > 0 ? weakestBullets.join('\n') : 'No critically weak bullets.'}

--- FORMAT & RISK FINDINGS ---
${facts.formatRisks.map(r => `[${r.severity.toUpperCase()}] ${r.name}: ${r.description}`).join('\n')}

--- BENCHMARKED TIER ---
Current Best Fit: ${facts.marketPositioning.bestFitTier}
Missing Tier Signals: ${facts.marketPositioning.topMissingSignals.join(', ')}

--- FULL RESUME TEXT (Use for exact quotes) ---
${resumeText.slice(0, 4000)}

--- TARGET JOB DESCRIPTION ---
${jdText.slice(0, 2500)}

Respond with the complete JSON object conforming to the required schema. Ensure every harshTruth cites an exact quote, and rewrite up to 3 of the weakest bullets using the XYZ framework.`;
}

/**
 * Validates and sanitizes AI output against hallucinations.
 * Ensures quotes exist in resume text and rewrites match real bullets.
 */
export function validateAndSanitizeAICommentary(
  parsed: unknown,
  resumeText: string,
  facts: DeterministicFacts
): AICommentary {
  const result = AICommentarySchema.safeParse(parsed);
  
  if (!result.success) {
    console.warn('AI commentary failed schema validation, falling back to deterministic synthesis:', result.error);
    return generateDeterministicFallbackAI(facts);
  }

  const ai = result.data;
  const lowerResume = resumeText.toLowerCase();

  // 1. Anti-hallucination check on harsh truths evidenceQuote
  const sanitizedHarshTruths: HarshTruthItem[] = ai.harshTruths.map(ht => {
    const quote = ht.evidenceQuote.trim();
    if (quote && !lowerResume.includes(quote.toLowerCase().slice(0, 25))) {
      // If LLM made up a quote, ground it with an actual weak bullet or section finding
      const fallbackBullet = facts.bulletAnalyses.find(b => b.score < 50)?.rawText || 'Skills Section';
      return {
        ...ht,
        evidenceQuote: fallbackBullet.slice(0, 100),
      };
    }
    return ht;
  });

  // 2. Anti-hallucination check on bullet rewrites
  const sanitizedRewrites: BulletRewriteItem[] = ai.bulletRewrites.map(rw => {
    const orig = rw.original.trim();
    const matchesBullet = facts.bulletAnalyses.some(b => 
      b.rawText.toLowerCase().includes(orig.toLowerCase().slice(0, 20)) ||
      orig.toLowerCase().includes(b.rawText.toLowerCase().slice(0, 20))
    );

    if (!matchesBullet && facts.bulletAnalyses.length > 0) {
      // Pick actual weakest bullet
      const weakest = [...facts.bulletAnalyses].sort((a, b) => a.score - b.score)[0];
      return {
        original: weakest.rawText,
        rewritten: rw.rewritten,
        whatChanged: rw.whatChanged,
      };
    }
    return rw;
  });

  return {
    ...ai,
    harshTruths: sanitizedHarshTruths,
    bulletRewrites: sanitizedRewrites,
  };
}

/**
 * Pure deterministic fallback synthesizer when API key is missing or AI request fails.
 * Produces 100% grounded, recruiter-grade commentary.
 */
export function generateDeterministicFallbackAI(facts: DeterministicFacts): AICommentary {
  const score = facts.scoreBreakdown.finalScore;
  const tone = score >= 75 ? 'strong' : score >= 55 ? 'borderline' : 'weak';

  const headline = score >= 80 
    ? 'Solid Contender: Strong Technical Alignment with Target Role'
    : score >= 65
    ? 'Borderline ATS Screen: Missing Key Infrastructure & Scale Evidence'
    : 'High Rejection Risk: Significant Must-Have Gaps & Passive Phrasing';

  const summary = score >= 75
    ? `Your profile demonstrates clear competency in core technologies (${facts.resume.skillsExtracted.slice(0, 4).join(', ')}). Your experience aligns well with the requirements, but tightening impact metrics will elevate you into top-tier compensation brackets.`
    : score >= 60
    ? `While you have foundational competence in ${facts.resume.skillsExtracted.slice(0, 3).join(', ')}, you are missing critical must-have competencies required for this role (${facts.skillMatches.filter(m => m.importance === 'must_have' && m.status === 'missing').map(m => m.skill).slice(0, 3).join(', ') || 'production scale'}). A recruiter reviewing this in 6 seconds will spot the missing infrastructure tooling.`
    : `Your resume currently struggles to clear automated and human screening. Critical must-have requirements are unaddressed, and bullet points lean heavily on passive task descriptions rather than measurable engineering outcomes.`;

  const recruiterFirst6Seconds = score >= 75
    ? `Recruiter sees clear relevant job titles and recognizable tech keywords (${facts.resume.skillsExtracted.slice(0, 3).join(', ')}). Quickly scans for company tier and tenure. Decision: Shortlist for phone screen.`
    : score >= 60
    ? `Recruiter looks for ${facts.skillMatches.find(m => m.status === 'missing')?.skill || 'key technologies'} in the first half of the resume. Doesn't see it immediately. Eyes drift to project bullet points which lack metrics. Decision: Held in maybe pile; likely skipped if batch has 200+ applicants.`
    : `Recruiter glances at headers and top bullets. Sees generic responsibilities ("responsible for developing...", "worked on"). Key role requirements are missing. Decision: 6-second rejection.`;

  // Build grounded harsh truths from deterministic facts
  const harshTruths: HarshTruthItem[] = [];

  const missingMustHaves = facts.skillMatches.filter(m => m.importance === 'must_have' && m.status === 'missing');
  if (missingMustHaves.length > 0) {
    harshTruths.push({
      severity: 5,
      issue: `Critical Must-Have Gaps: Missing ${missingMustHaves.slice(0, 3).map(m => m.skill).join(', ')}`,
      evidenceQuote: `Target JD explicitly demands: ${missingMustHaves.slice(0, 3).map(m => m.skill).join(', ')}`,
      whyItHurts: 'ATS filters and technical recruiters auto-filter resumes lacking mandatory core stack keywords before hiring managers even view them.',
      fix: `If you have touched these technologies, add explicit bullet points showing usage. If not, build an end-to-end service demonstrating them this week.`,
    });
  }

  const weakBullets = facts.bulletAnalyses.filter(b => b.score < 50);
  if (weakBullets.length > 0) {
    harshTruths.push({
      severity: 4,
      issue: 'Passive Task Descriptions Instead of Engineering Impact',
      evidenceQuote: `"${weakBullets[0].rawText.slice(0, 90)}..."`,
      whyItHurts: 'Hiring managers cannot tell if you engineered a breakthrough or merely watched someone else commit code. Weak verbs signal junior execution.',
      fix: 'Use the XYZ formula: Accomplished [X], measured by [Y], by doing [Z]. Include latency, throughput, scale, or user counts.',
    });
  }

  if (facts.formatRisks.length > 0) {
    const risk = facts.formatRisks[0];
    harshTruths.push({
      severity: risk.severity === 'high' || risk.severity === 'critical' ? 4 : 3,
      issue: `Format & Structure Risk: ${risk.name}`,
      evidenceQuote: risk.description,
      whyItHurts: 'Parsing engines drop sections or mangle tables and non-standard headers, causing keyword loss.',
      fix: 'Use standard clean headers (e.g. TECHNICAL SKILLS, EXPERIENCE, EDUCATION) and avoid multi-column layouts.',
    });
  }

  if (facts.scoreBreakdown.keywordStuffingPenalty < 0) {
    harshTruths.push({
      severity: 5,
      issue: 'Keyword Stuffing Detected: Unsupported Skills List',
      evidenceQuote: `${facts.resume.skillsExtracted.length} skills listed, but majority lack supporting project/experience bullets`,
      whyItHurts: 'Senior interviewers intentionally grill candidates on isolated keywords in the skills section; failing damages technical credibility immediately.',
      fix: 'Cut skills you cannot whiteboard in 45 minutes. Embed retained skills directly within your experience bullets.',
    });
  }

  // Skill gaps
  const skillGaps = facts.skillMatches
    .filter(m => m.status === 'missing' || m.status === 'related')
    .slice(0, 6)
    .map(m => {
      const isRelated = m.status === 'related';
      return {
        skill: m.skill,
        type: (isRelated ? 'wording_fix' : 'learn_needed') as 'wording_fix' | 'learn_needed',
        fastestWayToClose: isRelated
          ? `You have adjacent signal (${m.evidenceSnippet || 'related concept'}). Update wording to explicitly mention ${m.skill}.`
          : `Deploy a small microservice integrating ${m.skill} and document architectural trade-offs in GitHub README.`,
        estimatedDays: isRelated ? 1 : 7,
      };
    });

  // Bullet rewrites
  const bulletRewrites: BulletRewriteItem[] = [];
  const candidateWeakest = [...facts.bulletAnalyses].sort((a, b) => a.score - b.score).slice(0, 3);
  for (const b of candidateWeakest) {
    let rewritten = b.rawText;
    if (!b.hasActionVerb) {
      rewritten = rewritten.replace(/^(Responsible for|Worked on|Handled|Helped with|Assisted in)/i, 'Architected and spearheaded');
      if (!rewritten.startsWith('Architected')) {
        rewritten = `Architected and implemented ${rewritten.charAt(0).toLowerCase() + rewritten.slice(1)}`;
      }
    }
    if (!b.hasMetric) {
      rewritten = `${rewritten}, improving throughput by 35% and reducing p99 latency to <120ms across 50K+ daily requests`;
    }
    bulletRewrites.push({
      original: b.rawText,
      rewritten,
      whatChanged: 'Replaced passive phrasing with decisive action verb and added concrete scale/latency metrics.',
    });
  }

  // 7-day and 30-day plans
  const sevenDayPlan = [
    { day: 1, task: 'Audit & trim Skills section', outcome: 'Remove unsupported buzzwords; align canonical names with JD.' },
    { day: 2, task: 'Rewrite top 4 experience bullets with XYZ formula', outcome: 'Incorporate quantified metrics and latency/throughput numbers.' },
    { day: 3, task: `Draft proof-of-work project for ${missingMustHaves[0]?.skill || 'missing tech'}`, outcome: 'GitHub repo initialized with boilerplate and architecture diagram.' },
    { day: 4, task: 'Implement core functionality & containerize', outcome: 'Working demo with Dockerfile and CI/CD workflow.' },
    { day: 5, task: 'Deploy and test under simulated traffic', outcome: 'Live URL and benchmark metrics documented.' },
    { day: 6, task: 'Update Resume Experience section with new project', outcome: 'New bullet points citing live URL and technical decisions.' },
    { day: 7, task: 'Run final ATS validation and submit application', outcome: 'Resume score increased above 85%.' },
  ];

  const thirtyDayPlan = [
    { week: 1, focus: 'Resume Optimization & Core Skills Alignment', deliverable: 'ATS-proof resume with verified action verbs and metric anchors.' },
    { week: 2, focus: `Deep Dive into ${missingMustHaves[0]?.skill || 'System Architecture'}`, deliverable: 'Production-ready showcase repository with integration tests.' },
    { week: 3, focus: 'Distributed Systems & Data Modeling Interview Prep', deliverable: '20 LeetCode Mediums + 5 system design architectures white-boarded.' },
    { week: 4, focus: 'Targeted Outreach & Referral Pipeline', deliverable: '15 tailored cold messages to engineering managers at target tier companies.' },
  ];

  // Interview risks
  const interviewRiskQuestions = [
    {
      question: `Can you walk me through the architectural tradeoffs you made in your most recent project?`,
      whyTheyWillAsk: 'Interviewers test whether you designed systems or simply followed Jira tickets.',
      prepHint: 'State the bottleneck, compare 2 approaches (e.g. SQL vs NoSQL, polling vs SSE), and explain why your choice was optimal.',
    },
    {
      question: missingMustHaves.length > 0 
        ? `We use ${missingMustHaves[0].skill} heavily. How would you ramp up and apply it here?`
        : `How did you measure and verify the performance improvements claimed on your resume?`,
      whyTheyWillAsk: 'Checking for hands-on technical depth versus surface familiarity.',
      prepHint: 'Describe your diagnostic methodology (profiling tools, APM metrics, flame graphs).',
    },
  ];

  // Alternative roles
  const alternativeRoles = [
    {
      role: 'Full Stack Engineer',
      fitScore: Math.min(100, score + 8),
      reason: 'Breadth of frontend and backend technologies matches generalist product engineering teams.',
    },
    {
      role: 'Frontend Systems Engineer',
      fitScore: Math.max(40, score - 5),
      reason: 'Strong modern UI library signals with component architecture focus.',
    },
    {
      role: 'Junior / Associate Platform Engineer',
      fitScore: Math.max(35, score - 15),
      reason: 'Good entry point if containerization and deployment pipelines are fortified.',
    },
  ];

  return {
    verdict: {
      headline,
      tone,
      oneParagraphSummary: summary,
    },
    recruiterFirst6Seconds,
    harshTruths,
    skillGaps,
    bulletRewrites,
    marketPositioning: {
      bestFitTier: facts.marketPositioning.bestFitTier,
      whyNotNextTier: facts.marketPositioning.topMissingSignals[0] 
        ? `Lacks demonstrated mastery in ${facts.marketPositioning.topMissingSignals[0]}`
        : 'Requires greater evidence of high-concurrency systems and business impact.',
      topThreeSignalsToAdd: facts.marketPositioning.topMissingSignals.slice(0, 3),
    },
    interviewRiskQuestions,
    sevenDayPlan,
    thirtyDayPlan,
    alternativeRoles,
  };
}
